import type { Lesson, Quote } from "../types";
import { buildModules } from "./moduleDefs";

// ---------- Module 1 core lessons: Modern Standard Arabic (MSA) ----------
//
// Transliteration & vocalization convention used throughout this file:
//   - Diacritics (tashkeel) mark every word's internal vowel pattern so
//     pronunciation is unambiguous, but final case endings (i'rab) are
//     generally left unmarked (pausal/citation form) except where the
//     grammar rule itself is the teaching point (e.g. the accusative
//     khabar required after kana, or fixed adverbial-accusative tanwin
//     like sabahan/masa'an/jiddan), and except fixed greeting formulas
//     that are always taught fully vocalized.
//   - Romanization: ʾ = hamza, ʿ = ʿayn, ḥ = ح, kh = خ, dh = ذ, sh = ش,
//     ṣ = ص, ḍ = ض, ṭ = ط, ẓ = ظ, gh = غ, q = ق; ā/ī/ū mark long vowels,
//     aw/ay mark diphthongs. Sun-letter assimilation is reflected in the
//     transliteration of "al-" (e.g. ash-shams) where it is pronounced.

const lesson1: Lesson = {
  id: "ar-m1-l1",
  moduleId: "ar-m1",
  language: "ar",
  title: "greetings & introductions",
  size: "small",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l1-e1",
      type: "match",
      prompt: "match each greeting to its meaning",
      pairs: [
        { target: "مَرْحَبًا", transliteration: "marḥaban", english: "Hello" },
        { target: "صَبَاحُ الْخَيْرِ", transliteration: "ṣabāḥ al-khayr", english: "Good morning" },
        { target: "مَسَاءُ الْخَيْرِ", transliteration: "masāʾ al-khayr", english: "Good evening" },
        { target: "كَيْفَ حَالُكَ؟", transliteration: "kayfa ḥāluka", english: "How are you? (to a man)" },
        { target: "مَعَ السَّلَامَةِ", transliteration: "maʿa as-salāma", english: "Goodbye" },
      ],
    },
    {
      id: "ar-m1-l1-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "Hello, nice to meet you.",
      answer: "مَرْحَبًا، تَشَرَّفْنَا.",
      transliteration: "marḥaban, tasharrafnā.",
      term: { target: "تَشَرَّفْنَا", transliteration: "tasharrafnā", english: "nice / pleased to meet you" },
    },
    {
      id: "ar-m1-l1-e3",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "مَا اسْمُكَ؟",
      answer: "What is your name?",
      transliteration: "mā ismuka?",
      term: { target: "مَا اسْمُكَ؟", transliteration: "mā ismuka", english: "what is your name? (to a man)" },
    },
    {
      id: "ar-m1-l1-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "صَبَاحُ ___",
      transliteration: "ṣabāḥu ___",
      english: "Good morning (lit. \"morning of goodness\")",
      answer: "الْخَيْرِ",
      options: ["الْخَيْرِ", "النُّورِ", "السَّلَامَةِ", "اللِّقَاءِ"],
      term: { target: "صَبَاحُ الْخَيْرِ", transliteration: "ṣabāḥ al-khayr", english: "good morning" },
    },
    {
      id: "ar-m1-l1-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "اسْمِي سَارَة. تَشَرَّفْنَا.",
      transliteration: "ismī Sāra. Tasharrafnā.",
      english: "My name is Sara. Nice to meet you.",
      term: { target: "اسْمِي...", transliteration: "ismī", english: "my name is..." },
    },
    {
      id: "ar-m1-l1-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "مَسَاءُ الْخَيْرِ، كَيْفَ حَالُكَ؟",
      question: "What time of day is being greeted?",
      options: ["Morning", "Evening", "Night"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l1-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "Peace be upon you, and God's mercy.",
      words: ["السَّلَامُ", "عَلَيْكُمْ", "وَرَحْمَةُ", "اللَّهِ"],
    },
    {
      id: "ar-m1-l1-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "إِلَى اللِّقَاءِ.",
      english: "See you (until we meet).",
    },
    {
      id: "ar-m1-l1-e9",
      type: "explain",
      prompt: "introduce yourself in one or two sentences, in Arabic only",
      topic: "your name and that you're pleased to meet someone",
      targetLanguageHint: "اسْمِي ...",
      modelAnswer: "اسْمِي سَارَة. تَشَرَّفْنَا بِلِقَائِكَ.",
      modelAnswerEnglish: "My name is Sara. I'm pleased to meet you.",
    },
  ],
};

const lesson2: Lesson = {
  id: "ar-m1-l2",
  moduleId: "ar-m1",
  language: "ar",
  title: "numbers, colors & basic descriptions",
  size: "small",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l2-e1",
      type: "match",
      prompt: "match each number to its meaning",
      pairs: [
        { target: "وَاحِد", transliteration: "wāḥid", english: "One" },
        { target: "اِثْنَان", transliteration: "ithnān", english: "Two" },
        { target: "ثَلَاثَة", transliteration: "thalātha", english: "Three" },
        { target: "أَرْبَعَة", transliteration: "arbaʿa", english: "Four" },
        { target: "خَمْسَة", transliteration: "khamsa", english: "Five" },
      ],
    },
    {
      id: "ar-m1-l2-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "The car is red.",
      answer: "السَّيَّارَةُ حَمْرَاء.",
      transliteration: "as-sayyāra ḥamrāʾ.",
      term: { target: "حَمْرَاء", transliteration: "ḥamrāʾ", english: "red (feminine)" },
    },
    {
      id: "ar-m1-l2-e3",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "الْكِتَابُ أَزْرَق.",
      answer: "The book is blue.",
      transliteration: "al-kitāb azraq.",
      term: { target: "أَزْرَق", transliteration: "azraq", english: "blue (masculine)" },
    },
    {
      id: "ar-m1-l2-e4",
      type: "cloze",
      prompt: "fill in the blank (matching gender)",
      sentence: "بَيْتِي ___.",
      transliteration: "baytī ___.",
      english: "My house is big.",
      answer: "كَبِير",
      options: ["كَبِير", "كَبِيرَة", "صَغِير", "جَدِيد"],
      term: { target: "كَبِير", transliteration: "kabīr", english: "big (masculine)" },
    },
    {
      id: "ar-m1-l2-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "عِنْدِي قِطَّة صَغِيرَة.",
      transliteration: "ʿindī qiṭṭa ṣaghīra.",
      english: "I have a small cat.",
      term: { target: "صَغِيرَة", transliteration: "ṣaghīra", english: "small (feminine)" },
    },
    {
      id: "ar-m1-l2-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "عِنْدِي سَيَّارَة صَفْرَاء جَدِيدَة.",
      question: "What color is the car?",
      options: ["Red", "Yellow", "Green"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l2-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "I have seven small books.",
      words: ["عِنْدِي", "سَبْعَة", "كُتُب", "صَغِيرَة"],
    },
    {
      id: "ar-m1-l2-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "السَّمَاءُ زَرْقَاء.",
      english: "The sky is blue.",
    },
    {
      id: "ar-m1-l2-e9",
      type: "explain",
      prompt: "describe an object near you — its color and its size — in Arabic",
      topic: "an object's color and size",
      targetLanguageHint: "... كَبِير/كَبِيرَة، ... أَحْمَر/حَمْرَاء",
      modelAnswer: "حَقِيبَتِي صَغِيرَة وَحَمْرَاء.",
      modelAnswerEnglish: "My bag is small and red.",
    },
  ],
};

const lesson3: Lesson = {
  id: "ar-m1-l3",
  moduleId: "ar-m1",
  language: "ar",
  title: "family & people",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l3-e1",
      type: "match",
      prompt: "match each family member to its meaning",
      pairs: [
        { target: "أَب", transliteration: "ab", english: "Father" },
        { target: "أُم", transliteration: "umm", english: "Mother" },
        { target: "أَخ", transliteration: "akh", english: "Brother" },
        { target: "أُخْت", transliteration: "ukht", english: "Sister" },
        { target: "صَدِيق", transliteration: "ṣadīq", english: "Friend (male)" },
      ],
    },
    {
      id: "ar-m1-l3-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "This is my father.",
      answer: "هَذَا أَبِي.",
      transliteration: "hādhā abī.",
      term: { target: "أَبِي", transliteration: "abī", english: "my father" },
    },
    {
      id: "ar-m1-l3-e3",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "This is my sister.",
      answer: "هَذِهِ أُخْتِي.",
      transliteration: "hādhihi ukhtī.",
      term: { target: "أُخْتِي", transliteration: "ukhtī", english: "my sister" },
    },
    {
      id: "ar-m1-l3-e4",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "مَنْ هَذَا؟ هَذَا أَخِي.",
      answer: "Who is this? This is my brother.",
      transliteration: "man hādhā? hādhā akhī.",
      term: { target: "مَنْ هَذَا؟", transliteration: "man hādhā", english: "who is this? (m)" },
    },
    {
      id: "ar-m1-l3-e5",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "___ جَدَّتِي، وَهَذَا جَدِّي.",
      transliteration: "___ jaddatī, wa-hādhā jaddī.",
      english: "This is my grandmother, and this is my grandfather.",
      answer: "هَذِهِ",
      options: ["هَذِهِ", "هَذَا", "هُوَ", "هِيَ"],
      term: { target: "جَدَّة", transliteration: "jadda", english: "grandmother" },
    },
    {
      id: "ar-m1-l3-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "عِنْدِي ثَلَاثَة ___.",
      transliteration: "ʿindī thalāthat ___.",
      english: "I have three siblings.",
      answer: "إِخْوَة",
      options: ["إِخْوَة", "أَخَوَات", "بَنَات", "أَوْلَاد"],
      term: { target: "إِخْوَة", transliteration: "ikhwa", english: "siblings / brothers (plural)" },
    },
    {
      id: "ar-m1-l3-e7",
      type: "speak",
      prompt: "say this aloud",
      target: "هَذِهِ عَائِلَتِي. عَائِلَتِي كَبِيرَة.",
      transliteration: "hādhihi ʿāʾilatī. ʿāʾilatī kabīra.",
      english: "This is my family. My family is big.",
      term: { target: "عَائِلَة", transliteration: "ʿāʾila", english: "family" },
    },
    {
      id: "ar-m1-l3-e8",
      type: "speak",
      prompt: "say this aloud",
      target: "زَوْجِي اسْمُهُ أَحْمَد.",
      transliteration: "zawjī ismuh Aḥmad.",
      english: "My husband's name is Ahmad.",
      term: { target: "زَوْج", transliteration: "zawj", english: "husband" },
    },
    {
      id: "ar-m1-l3-e9",
      type: "listen",
      prompt: "listen and answer",
      audioText: "هَذَا أَبِي، وَهَذِهِ أُمِّي، وَهَذِهِ أُخْتِي الصَّغِيرَة.",
      question: "Who is described as young/little?",
      options: ["Father", "Mother", "Younger sister"],
      correctIndex: 2,
    },
    {
      id: "ar-m1-l3-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "This is my new friend, Layla.",
      words: ["هَذِهِ", "صَدِيقَتِي", "الْجَدِيدَة", "لَيْلَى"],
    },
    {
      id: "ar-m1-l3-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "هَذِهِ جَدَّتِي وَهَذَا جَدِّي.",
      english: "This is my grandmother and this is my grandfather.",
    },
    {
      id: "ar-m1-l3-e12",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "لَدَيْنَا ابْن وَابْنَة.",
      answer: "We have a son and a daughter.",
      transliteration: "ladaynā ibn wa-ibna.",
      term: { target: "لَدَيْنَا", transliteration: "ladaynā", english: "we have" },
    },
    {
      id: "ar-m1-l3-e13",
      type: "explain",
      prompt: "describe your family in two short sentences, in Arabic only",
      topic: "family members and one description",
      targetLanguageHint: "عِنْدِي.../عَائِلَتِي...",
      modelAnswer: "عِنْدِي أُم وَأَب وَأُخْت. عَائِلَتِي صَغِيرَة.",
      modelAnswerEnglish: "I have a mother, a father, and a sister. My family is small.",
    },
  ],
};

const lesson4: Lesson = {
  id: "ar-m1-l4",
  moduleId: "ar-m1",
  language: "ar",
  title: "daily routine & time",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l4-e1",
      type: "match",
      prompt: "match each verb to its meaning",
      pairs: [
        { target: "أَسْتَيْقِظُ", transliteration: "astayqiẓ", english: "I wake up" },
        { target: "آكُلُ", transliteration: "ākul", english: "I eat" },
        { target: "أَذْهَبُ", transliteration: "adhhab", english: "I go" },
        { target: "أَعْمَلُ", transliteration: "aʿmal", english: "I work" },
        { target: "أَنَامُ", transliteration: "anām", english: "I sleep" },
      ],
    },
    {
      id: "ar-m1-l4-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "I wake up at seven o'clock.",
      answer: "أَسْتَيْقِظُ فِي السَّاعَةِ السَّابِعَة.",
      transliteration: "astayqiẓ fī as-sāʿa as-sābiʿa.",
      term: { target: "أَسْتَيْقِظُ", transliteration: "astayqiẓ", english: "I wake up" },
    },
    {
      id: "ar-m1-l4-e3",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "I go to work every day.",
      answer: "أَذْهَبُ إِلَى الْعَمَلِ كُلَّ يَوْم.",
      transliteration: "adhhab ilā al-ʿamal kulla yawm.",
      term: { target: "أَذْهَبُ", transliteration: "adhhab", english: "I go" },
    },
    {
      id: "ar-m1-l4-e4",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "مَاذَا تَأْكُلُ فِي الصَّبَاحِ؟",
      answer: "What do you eat in the morning?",
      transliteration: "mādhā taʾkul fī aṣ-ṣabāḥ?",
      term: { target: "مَاذَا تَأْكُلُ؟", transliteration: "mādhā taʾkul", english: "what do you eat?" },
    },
    {
      id: "ar-m1-l4-e5",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "كَمِ ___؟",
      transliteration: "kam ___?",
      english: "What time is it?",
      answer: "السَّاعَة",
      options: ["السَّاعَة", "الْوَقْت", "الْيَوْم", "الْآن"],
      term: { target: "كَمِ السَّاعَةُ؟", transliteration: "kam as-sāʿa", english: "what time is it?" },
    },
    {
      id: "ar-m1-l4-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "أَنَا ___ فِي السَّاعَةِ الْعَاشِرَة مَسَاءً.",
      transliteration: "anā ___ fī as-sāʿa al-ʿāshira masāʾan.",
      english: "I sleep at ten o'clock in the evening.",
      answer: "أَنَامُ",
      options: ["أَنَامُ", "آكُلُ", "أَعْمَلُ", "أَذْهَبُ"],
      term: { target: "أَنَامُ", transliteration: "anām", english: "I sleep" },
    },
    {
      id: "ar-m1-l4-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "أَسْتَيْقِظُ ___ كُلَّ يَوْم.",
      transliteration: "astayqiẓ ___ kulla yawm.",
      english: "I wake up early every day.",
      answer: "مُبَكِّرًا",
      options: ["مُبَكِّرًا", "مُتَأَخِّرًا", "الْآن", "غَدًا"],
      term: { target: "مُبَكِّرًا", transliteration: "mubakkiran", english: "early" },
    },
    {
      id: "ar-m1-l4-e8",
      type: "speak",
      prompt: "say this aloud",
      target: "أَذْهَبُ إِلَى الْمَدْرَسَةِ صَبَاحًا، وَأَعُودُ إِلَى الْبَيْتِ مَسَاءً.",
      transliteration: "adhhab ilā al-madrasa ṣabāḥan, wa-aʿūd ilā al-bayt masāʾan.",
      english: "I go to school in the morning, and I return home in the evening.",
      term: { target: "أَعُودُ", transliteration: "aʿūd", english: "I return" },
    },
    {
      id: "ar-m1-l4-e9",
      type: "speak",
      prompt: "say this aloud",
      target: "أَوَّلًا أَسْتَيْقِظُ، ثُمَّ آكُلُ الْفُطُور.",
      transliteration: "awwalan astayqiẓ, thumma ākul al-fuṭūr.",
      english: "First I wake up, then I eat breakfast.",
      term: { target: "ثُمَّ", transliteration: "thumma", english: "then" },
    },
    {
      id: "ar-m1-l4-e10",
      type: "listen",
      prompt: "listen and answer",
      audioText: "فِي كُلِّ يَوْم أَدْرُسُ فِي الصَّبَاحِ، وَأَعْمَلُ فِي الْمَسَاءِ.",
      question: "When does the speaker study?",
      options: ["In the morning", "In the evening", "At night"],
      correctIndex: 0,
    },
    {
      id: "ar-m1-l4-e11",
      type: "reorder",
      prompt: "put the words in order",
      english: "I wake up early every day.",
      words: ["أَسْتَيْقِظُ", "مُبَكِّرًا", "كُلَّ", "يَوْم"],
    },
    {
      id: "ar-m1-l4-e12",
      type: "dictation",
      prompt: "type what you hear",
      target: "أَنَا أَذْهَبُ إِلَى الْبَيْتِ الْآن.",
      english: "I am going home now.",
    },
    {
      id: "ar-m1-l4-e13",
      type: "explain",
      prompt: "describe your daily routine in two or three short sentences, in Arabic only",
      topic: "wake time, one activity, sleep time",
      targetLanguageHint: "أَسْتَيْقِظُ فِي.../ثُمَّ.../أَنَامُ فِي...",
      modelAnswer: "أَسْتَيْقِظُ فِي السَّاعَةِ السَّابِعَة. أَذْهَبُ إِلَى الْعَمَلِ. أَنَامُ فِي السَّاعَةِ الْحَادِيَةَ عَشْرَة.",
      modelAnswerEnglish: "I wake up at seven o'clock. I go to work. I sleep at eleven o'clock.",
    },
  ],
};

const lesson5: Lesson = {
  id: "ar-m1-l5",
  moduleId: "ar-m1",
  language: "ar",
  title: "food & dining",
  size: "large",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l5-e1",
      type: "match",
      prompt: "match each food word to its meaning",
      pairs: [
        { target: "خُبْز", transliteration: "khubz", english: "Bread" },
        { target: "أَرُزّ", transliteration: "aruzz", english: "Rice" },
        { target: "لَحْم", transliteration: "laḥm", english: "Meat" },
        { target: "دَجَاج", transliteration: "dajāj", english: "Chicken" },
        { target: "سَمَك", transliteration: "samak", english: "Fish" },
        { target: "مَاء", transliteration: "māʾ", english: "Water" },
      ],
    },
    {
      id: "ar-m1-l5-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "I want water, please.",
      answer: "أُرِيدُ مَاء مِنْ فَضْلِكَ.",
      transliteration: "urīd māʾ min faḍlika.",
      term: { target: "أُرِيدُ", transliteration: "urīd", english: "I want" },
    },
    {
      id: "ar-m1-l5-e3",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "I am hungry and thirsty.",
      answer: "أَنَا جَائِع وَعَطْشَان.",
      transliteration: "anā jāʾiʿ wa-ʿaṭshān.",
      term: { target: "جَائِع", transliteration: "jāʾiʿ", english: "hungry (masculine)" },
    },
    {
      id: "ar-m1-l5-e4",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "هَلْ تُرِيدُ قَهْوَة أَمْ شَاي؟",
      answer: "Do you want coffee or tea?",
      transliteration: "hal turīd qahwa am shāy?",
      term: { target: "أَمْ", transliteration: "am", english: "or (used in questions)" },
    },
    {
      id: "ar-m1-l5-e5",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "الطَّعَامُ لَذِيذ جِدًّا.",
      answer: "The food is very delicious.",
      transliteration: "aṭ-ṭaʿām ladhīdh jiddan.",
      term: { target: "لَذِيذ", transliteration: "ladhīdh", english: "delicious (masculine)" },
    },
    {
      id: "ar-m1-l5-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "أَنَا ___ عَصِير التُّفَّاح.",
      transliteration: "anā ___ ʿaṣīr at-tuffāḥ.",
      english: "I like apple juice.",
      answer: "أُحِبُّ",
      options: ["أُحِبُّ", "آكُلُ", "أَشْرَبُ", "أُرِيدُ"],
      term: { target: "أُحِبُّ", transliteration: "uḥibb", english: "I like / love" },
    },
    {
      id: "ar-m1-l5-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "مِنْ ___، أُرِيدُ الْفَاتُورَة.",
      transliteration: "min ___, urīd al-fātūra.",
      english: "Please, I want the bill.",
      answer: "فَضْلِكَ",
      options: ["فَضْلِكَ", "فَضْلِكِ", "هُنَا", "الْآن"],
      term: { target: "الْفَاتُورَة", transliteration: "al-fātūra", english: "the bill" },
    },
    {
      id: "ar-m1-l5-e8",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "أَنَا لَا ___ اللَّحْم.",
      transliteration: "anā lā ___ al-laḥm.",
      english: "I don't eat meat.",
      answer: "آكُلُ",
      options: ["آكُلُ", "أَشْرَبُ", "أُرِيدُ", "أُحِبُّ"],
      term: { target: "لَا آكُلُ", transliteration: "lā ākul", english: "I don't eat" },
    },
    {
      id: "ar-m1-l5-e9",
      type: "speak",
      prompt: "say this aloud",
      target: "أَنَا جَائِع. أُرِيدُ أَنْ آكُلَ.",
      transliteration: "anā jāʾiʿ. urīd an ākul.",
      english: "I'm hungry. I want to eat.",
      term: { target: "أُرِيدُ أَنْ", transliteration: "urīd an", english: "I want to (+ verb)" },
    },
    {
      id: "ar-m1-l5-e10",
      type: "speak",
      prompt: "say this aloud",
      target: "هَلْ عِنْدَكُمْ قَائِمَةُ الطَّعَامِ، مِنْ فَضْلِكَ؟",
      transliteration: "hal ʿindakum qāʾimat aṭ-ṭaʿām, min faḍlika?",
      english: "Do you have a menu, please?",
      term: { target: "قَائِمَةُ الطَّعَامِ", transliteration: "qāʾimat aṭ-ṭaʿām", english: "the menu" },
    },
    {
      id: "ar-m1-l5-e11",
      type: "speak",
      prompt: "say this aloud",
      target: "النَّادِلُ لَطِيف جِدًّا.",
      transliteration: "an-nādil laṭīf jiddan.",
      english: "The waiter is very nice.",
      term: { target: "نَادِل", transliteration: "nādil", english: "waiter" },
    },
    {
      id: "ar-m1-l5-e12",
      type: "listen",
      prompt: "listen and answer",
      audioText: "أَنَا أُرِيدُ دَجَاجًا وَأَرُزًّا، وَصَدِيقِي يُرِيدُ سَمَكًا.",
      question: "What does the speaker's friend want?",
      options: ["Chicken", "Rice", "Fish"],
      correctIndex: 2,
    },
    {
      id: "ar-m1-l5-e13",
      type: "listen",
      prompt: "listen and answer",
      audioText: "الْقَهْوَةُ سَاخِنَة وَالْعَصِيرُ بَارِد.",
      question: "Which drink is cold?",
      options: ["Coffee", "Juice", "Tea"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l5-e14",
      type: "reorder",
      prompt: "put the words in order",
      english: "I want a cup of tea with milk.",
      words: ["أُرِيدُ", "كُوبَ", "شَاي", "بِحَلِيب"],
    },
    {
      id: "ar-m1-l5-e15",
      type: "reorder",
      prompt: "put the words in order",
      english: "The food here is very delicious.",
      words: ["الطَّعَامُ", "هُنَا", "لَذِيذ", "جِدًّا"],
    },
    {
      id: "ar-m1-l5-e16",
      type: "dictation",
      prompt: "type what you hear",
      target: "أَنَا عَطْشَان. أُرِيدُ مَاء، مِنْ فَضْلِكَ.",
      english: "I'm thirsty. I want water, please.",
    },
    {
      id: "ar-m1-l5-e17",
      type: "dictation",
      prompt: "type what you hear",
      target: "الْعَشَاءُ جَاهِز.",
      english: "Dinner is ready.",
    },
    {
      id: "ar-m1-l5-e18",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "مَاذَا تَأْكُلُ فِي الْغَدَاء عَادَةً؟",
      answer: "What do you usually eat for lunch?",
      transliteration: "mādhā taʾkul fī al-ghadāʾ ʿādatan?",
      term: { target: "عَادَةً", transliteration: "ʿādatan", english: "usually" },
    },
    {
      id: "ar-m1-l5-e19",
      type: "explain",
      prompt: "order a meal at a restaurant, in Arabic (two or three sentences)",
      topic: "greet the waiter, say what you want to eat and drink, say please",
      targetLanguageHint: "أُرِيدُ.../مِنْ فَضْلِكَ",
      modelAnswer: "مَسَاءُ الْخَيْرِ. أُرِيدُ دَجَاجًا وَأَرُزًّا، وَعَصِيرَ بُرْتُقَال مِنْ فَضْلِكَ.",
      modelAnswerEnglish: "Good evening. I want chicken and rice, and orange juice, please.",
    },
  ],
};

const lesson6: Lesson = {
  id: "ar-m1-l6",
  moduleId: "ar-m1",
  language: "ar",
  title: "home & directions",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l6-e1",
      type: "match",
      prompt: "match each room to its meaning",
      pairs: [
        { target: "غُرْفَةُ النَّوْمِ", transliteration: "ghurfat an-nawm", english: "Bedroom" },
        { target: "الْمَطْبَخ", transliteration: "al-maṭbakh", english: "Kitchen" },
        { target: "الْحَمَّام", transliteration: "al-ḥammām", english: "Bathroom" },
        { target: "غُرْفَةُ الْجُلُوسِ", transliteration: "ghurfat al-julūs", english: "Living room" },
        { target: "الشَّارِع", transliteration: "ash-shāriʿ", english: "Street" },
      ],
    },
    {
      id: "ar-m1-l6-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "Where is the kitchen?",
      answer: "أَيْنَ الْمَطْبَخُ؟",
      transliteration: "ayna al-maṭbakh?",
      term: { target: "أَيْنَ؟", transliteration: "ayna", english: "where?" },
    },
    {
      id: "ar-m1-l6-e3",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "The bathroom is next to the bedroom.",
      answer: "الْحَمَّامُ بِجَانِبِ غُرْفَةِ النَّوْمِ.",
      transliteration: "al-ḥammām bijānibi ghurfat an-nawm.",
      term: { target: "بِجَانِبِ", transliteration: "bijānibi", english: "next to" },
    },
    {
      id: "ar-m1-l6-e4",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "الْمَكْتَبَةُ أَمَامَ الْبَيْتِ.",
      answer: "The library is in front of the house.",
      transliteration: "al-maktaba amāma al-bayt.",
      term: { target: "أَمَامَ", transliteration: "amāma", english: "in front of" },
    },
    {
      id: "ar-m1-l6-e5",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "الْحَدِيقَةُ ___ الْبَيْتِ.",
      transliteration: "al-ḥadīqa ___ al-bayt.",
      english: "The garden is behind the house.",
      answer: "خَلْفَ",
      options: ["خَلْفَ", "أَمَامَ", "بِجَانِبِ", "دَاخِلَ"],
      term: { target: "خَلْفَ", transliteration: "khalfa", english: "behind" },
    },
    {
      id: "ar-m1-l6-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "الْمَطْعَمُ ___ مِنْ هُنَا.",
      transliteration: "al-maṭʿam ___ min hunā.",
      english: "The restaurant is near here.",
      answer: "قَرِيب",
      options: ["قَرِيب", "بَعِيد", "يَمِين", "يَسَار"],
      term: { target: "قَرِيب مِنْ", transliteration: "qarīb min", english: "near" },
    },
    {
      id: "ar-m1-l6-e7",
      type: "speak",
      prompt: "say this aloud",
      target: "اِذْهَبْ مُبَاشَرَةً ثُمَّ انْعَطِفْ يَمِينًا.",
      transliteration: "idhhab mubāsharatan thumma inʿaṭif yamīnan.",
      english: "Go straight, then turn right.",
      term: { target: "اِنْعَطِفْ", transliteration: "inʿaṭif", english: "turn (command)" },
    },
    {
      id: "ar-m1-l6-e8",
      type: "speak",
      prompt: "say this aloud",
      target: "الْبَنْكُ عَلَى يَسَارِكَ.",
      transliteration: "al-bank ʿalā yasārika.",
      english: "The bank is on your left.",
      term: { target: "يَسَار", transliteration: "yasār", english: "left" },
    },
    {
      id: "ar-m1-l6-e9",
      type: "listen",
      prompt: "listen and answer",
      audioText: "اُخْرُجْ مِنَ الْبَيْتِ، اِذْهَبْ مُبَاشَرَةً، ثُمَّ انْعَطِفْ يَسَارًا عِنْدَ الشَّارِعِ.",
      question: "Which direction do you turn at the street?",
      options: ["Right", "Left", "Straight"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l6-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "The kitchen is next to the living room.",
      words: ["الْمَطْبَخُ", "بِجَانِبِ", "غُرْفَةِ", "الْجُلُوسِ"],
    },
    {
      id: "ar-m1-l6-e11",
      type: "reorder",
      prompt: "put the words in order",
      english: "Turn left, then go straight.",
      words: ["اِنْعَطِفْ", "يَسَارًا", "ثُمَّ", "اِذْهَبْ", "مُبَاشَرَةً"],
    },
    {
      id: "ar-m1-l6-e12",
      type: "dictation",
      prompt: "type what you hear",
      target: "بَيْتِي كَبِير وَقَرِيب مِنَ الْمَدْرَسَةِ.",
      english: "My house is big and near the school.",
    },
    {
      id: "ar-m1-l6-e13",
      type: "explain",
      prompt: "give simple directions from your house to a nearby shop, in Arabic",
      topic: "straight, turn, near/far",
      targetLanguageHint: "اِذْهَبْ.../انْعَطِفْ.../قَرِيب مِنْ...",
      modelAnswer: "اِذْهَبْ مُبَاشَرَةً، ثُمَّ انْعَطِفْ يَمِينًا. الْمَحَلُّ قَرِيب مِنَ الْبَيْتِ.",
      modelAnswerEnglish: "Go straight, then turn right. The shop is near the house.",
    },
  ],
};

const lesson7: Lesson = {
  id: "ar-m1-l7",
  moduleId: "ar-m1",
  language: "ar",
  title: "shopping & money",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l7-e1",
      type: "match",
      prompt: "match each word to its meaning",
      pairs: [
        { target: "سُوق", transliteration: "sūq", english: "Market" },
        { target: "مَحَلّ", transliteration: "maḥall", english: "Shop" },
        { target: "نُقُود", transliteration: "nuqūd", english: "Money" },
        { target: "رَخِيص", transliteration: "rakhīṣ", english: "Cheap" },
        { target: "غَالٍ", transliteration: "ghālin", english: "Expensive" },
      ],
    },
    {
      id: "ar-m1-l7-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "How much is this?",
      answer: "كَمْ ثَمَنُ هَذَا؟",
      transliteration: "kam thaman hādhā?",
      term: { target: "كَمْ ثَمَنُ هَذَا؟", transliteration: "kam thaman hādhā", english: "how much is this?" },
    },
    {
      id: "ar-m1-l7-e3",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "I want to buy a new shirt.",
      answer: "أُرِيدُ أَنْ أَشْتَرِيَ قَمِيصًا جَدِيدًا.",
      transliteration: "urīd an ashtariya qamīṣan jadīdan.",
      term: { target: "أَشْتَرِي", transliteration: "ashtarī", english: "I buy" },
    },
    {
      id: "ar-m1-l7-e4",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "هَذَا رَخِيص، وَذَلِكَ غَالٍ.",
      answer: "This is cheap, and that is expensive.",
      transliteration: "hādhā rakhīṣ, wa-dhālika ghālin.",
      term: { target: "غَالٍ", transliteration: "ghālin", english: "expensive" },
    },
    {
      id: "ar-m1-l7-e5",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "أُرِيدُ أَنْ ___ نَقْدًا.",
      transliteration: "urīd an ___ naqdan.",
      english: "I want to pay in cash.",
      answer: "أَدْفَعَ",
      options: ["أَدْفَعَ", "أَشْتَرِيَ", "أَقْبَلَ", "أَسْأَلَ"],
      term: { target: "أَدْفَعُ", transliteration: "adfaʿ", english: "I pay" },
    },
    {
      id: "ar-m1-l7-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "هَذَا الْقَمِيصُ ___ مِنْ ذَلِكَ.",
      transliteration: "hādhā al-qamīṣ ___ min dhālika.",
      english: "This shirt is cheaper than that one.",
      answer: "أَرْخَصُ",
      options: ["أَرْخَصُ", "أَغْلَى", "أَكْبَرُ", "أَصْغَرُ"],
      term: { target: "أَرْخَصُ", transliteration: "arkhaṣ", english: "cheaper (comparative)" },
    },
    {
      id: "ar-m1-l7-e7",
      type: "speak",
      prompt: "say this aloud",
      target: "هَلْ عِنْدَكُمْ مَقَاس أَكْبَرُ؟",
      transliteration: "hal ʿindakum maqās akbar?",
      english: "Do you have a bigger size?",
      term: { target: "مَقَاس", transliteration: "maqās", english: "size" },
    },
    {
      id: "ar-m1-l7-e8",
      type: "speak",
      prompt: "say this aloud",
      target: "هَلْ تَقْبَلُونَ بِطَاقَةَ الِائْتِمَانِ؟",
      transliteration: "hal taqbalūn biṭāqat al-iʾtimān?",
      english: "Do you accept credit card?",
      term: { target: "بِطَاقَةُ الِائْتِمَانِ", transliteration: "biṭāqat al-iʾtimān", english: "credit card" },
    },
    {
      id: "ar-m1-l7-e9",
      type: "listen",
      prompt: "listen and answer",
      audioText: "هَذَا الْمَحَلُّ عِنْدَهُ خَصْم كَبِير الْيَوْمَ، كُلُّ شَيْء رَخِيص.",
      question: "What is happening at the shop today?",
      options: ["Everything is expensive", "There is a big discount", "The shop is closed"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l7-e10",
      type: "listen",
      prompt: "listen and answer",
      audioText: "ثَمَنُ الْقَمِيصِ عِشْرُونَ دِينَارًا.",
      question: "How much does the shirt cost?",
      options: ["Ten dinars", "Twenty dinars", "Twelve dinars"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l7-e11",
      type: "reorder",
      prompt: "put the words in order",
      english: "How much is this bag?",
      words: ["كَمْ", "ثَمَنُ", "هَذِهِ", "الْحَقِيبَةِ؟"],
    },
    {
      id: "ar-m1-l7-e12",
      type: "dictation",
      prompt: "type what you hear",
      target: "أُرِيدُ إِيصَالًا، مِنْ فَضْلِكَ.",
      english: "I want a receipt, please.",
    },
    {
      id: "ar-m1-l7-e13",
      type: "explain",
      prompt: "bargain politely for a lower price, in Arabic (one or two sentences)",
      topic: "say it's expensive and ask for a discount",
      targetLanguageHint: "هَذَا غَالٍ.../هَلْ يُوجَدُ خَصْم؟",
      modelAnswer: "هَذَا غَالٍ قَلِيلًا. هَلْ يُوجَدُ خَصْم؟",
      modelAnswerEnglish: "This is a little expensive. Is there a discount?",
    },
  ],
};

const lesson8: Lesson = {
  id: "ar-m1-l8",
  moduleId: "ar-m1",
  language: "ar",
  title: "weather, small talk & hobbies bridge",
  size: "large",
  kind: "core",
  exercises: [
    {
      id: "ar-m1-l8-e1",
      type: "match",
      prompt: "match each word to its meaning",
      pairs: [
        { target: "حَارّ", transliteration: "ḥārr", english: "Hot" },
        { target: "بَارِد", transliteration: "bārid", english: "Cold" },
        { target: "مُشْمِس", transliteration: "mushmis", english: "Sunny" },
        { target: "مُمْطِر", transliteration: "mumṭir", english: "Rainy" },
        { target: "صَيْف", transliteration: "ṣayf", english: "Summer" },
        { target: "شِتَاء", transliteration: "shitāʾ", english: "Winter" },
      ],
    },
    {
      id: "ar-m1-l8-e2",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "The weather is hot today.",
      answer: "الطَّقْسُ حَارّ الْيَوْمَ.",
      transliteration: "aṭ-ṭaqs ḥārr al-yawm.",
      term: { target: "الطَّقْس", transliteration: "aṭ-ṭaqs", english: "the weather" },
    },
    {
      id: "ar-m1-l8-e3",
      type: "translate",
      prompt: "translate to Arabic",
      direction: "to-target",
      source: "It's rainy in winter.",
      answer: "الدُّنْيَا مُمْطِرَة فِي الشِّتَاءِ.",
      transliteration: "ad-dunyā mumṭira fī ash-shitāʾ.",
      term: { target: "مُمْطِر", transliteration: "mumṭir", english: "rainy" },
    },
    {
      id: "ar-m1-l8-e4",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "أُحِبُّ فَصْلَ الرَّبِيعِ لِأَنَّ الْجَوَّ مُعْتَدِل.",
      answer: "I love spring because the weather is mild.",
      transliteration: "uḥibb faṣl ar-rabīʿ liʾanna al-jaww muʿtadil.",
      term: { target: "لِأَنَّ", transliteration: "liʾanna", english: "because" },
    },
    {
      id: "ar-m1-l8-e5",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "مَا هِيَ هِوَايَتُكَ؟",
      answer: "What is your hobby?",
      transliteration: "mā hiya hiwāyatuka?",
      term: { target: "هِوَايَة", transliteration: "hiwāya", english: "hobby" },
    },
    {
      id: "ar-m1-l8-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "أَنَا ___ الْقِرَاءَةَ وَالسِّبَاحَةَ.",
      transliteration: "anā ___ al-qirāʾa wa-as-sibāḥa.",
      english: "I love reading and swimming.",
      answer: "أُحِبُّ",
      options: ["أُحِبُّ", "أَذْهَبُ", "أُرِيدُ", "أَعْمَلُ"],
      term: { target: "قِرَاءَة", transliteration: "qirāʾa", english: "reading" },
    },
    {
      id: "ar-m1-l8-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "فِي الصَّيْفِ، الطَّقْسُ ___ جِدًّا.",
      transliteration: "fī aṣ-ṣayf, aṭ-ṭaqs ___ jiddan.",
      english: "In summer, the weather is very hot.",
      answer: "حَارّ",
      options: ["حَارّ", "بَارِد", "مُعْتَدِل", "غَائِم"],
      term: { target: "صَيْف", transliteration: "ṣayf", english: "summer" },
    },
    {
      id: "ar-m1-l8-e8",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "هَلْ تُحِبُّ ___ فِي وَقْتِ فَرَاغِكَ؟",
      transliteration: "hal tuḥibb ___ fī waqt farāghika?",
      english: "Do you like sports in your free time?",
      answer: "الرِّيَاضَة",
      options: ["الرِّيَاضَة", "الْمُوسِيقَى", "السَّفَر", "الْقِرَاءَة"],
      term: { target: "فِي وَقْتِ الْفَرَاغِ", transliteration: "fī waqt al-farāgh", english: "in [one's] free time" },
    },
    {
      id: "ar-m1-l8-e9",
      type: "speak",
      prompt: "say this aloud",
      target: "هِوَايَتِي الْمُفَضَّلَةُ هِيَ الْمُوسِيقَى.",
      transliteration: "hiwāyatī al-mufaḍḍala hiya al-mūsīqā.",
      english: "My favorite hobby is music.",
      term: { target: "مُفَضَّل", transliteration: "mufaḍḍal", english: "favorite" },
    },
    {
      id: "ar-m1-l8-e10",
      type: "speak",
      prompt: "say this aloud",
      target: "فِي فَصْلِ الْخَرِيفِ، أُحِبُّ السَّفَرَ.",
      transliteration: "fī faṣl al-kharīf, uḥibb as-safar.",
      english: "In autumn, I love traveling.",
      term: { target: "سَفَر", transliteration: "safar", english: "travel" },
    },
    {
      id: "ar-m1-l8-e11",
      type: "speak",
      prompt: "say this aloud",
      target: "كَيْفَ الطَّقْسُ الْيَوْمَ؟ أَظُنُّ أَنَّهُ جَمِيل.",
      transliteration: "kayfa aṭ-ṭaqs al-yawm? aẓunn annahu jamīl.",
      english: "How is the weather today? I think it's nice.",
      term: { target: "أَظُنُّ", transliteration: "aẓunn", english: "I think" },
    },
    {
      id: "ar-m1-l8-e12",
      type: "listen",
      prompt: "listen and answer",
      audioText: "غَدًا سَيَكُونُ الطَّقْسُ غَائِمًا وَبَارِدًا، لِذَلِكَ سَآخُذُ مِعْطَفِي.",
      question: "What will the weather be like tomorrow?",
      options: ["Sunny and hot", "Cloudy and cold", "Mild and rainy"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l8-e13",
      type: "listen",
      prompt: "listen and answer",
      audioText: "فِي وَقْتِ فَرَاغِي، أَقْرَأُ الْكُتُبَ وَأَسْتَمِعُ إِلَى الْمُوسِيقَى.",
      question: "What does the speaker do in their free time?",
      options: ["Swims and travels", "Reads books and listens to music", "Plays sports"],
      correctIndex: 1,
    },
    {
      id: "ar-m1-l8-e14",
      type: "reorder",
      prompt: "put the words in order",
      english: "What's the weather like in your country today?",
      words: ["كَيْفَ", "الطَّقْسُ", "فِي", "بَلَدِكَ", "الْيَوْمَ؟"],
    },
    {
      id: "ar-m1-l8-e15",
      type: "reorder",
      prompt: "put the words in order",
      english: "My favorite season is autumn.",
      words: ["فَصْلِي", "الْمُفَضَّلُ", "هُوَ", "الْخَرِيفُ"],
    },
    {
      id: "ar-m1-l8-e16",
      type: "dictation",
      prompt: "type what you hear",
      target: "أُحِبُّ الطَّقْسَ الْمُعْتَدِلَ فِي الرَّبِيعِ.",
      english: "I love the mild weather in spring.",
    },
    {
      id: "ar-m1-l8-e17",
      type: "dictation",
      prompt: "type what you hear",
      target: "مَا هِيَ هِوَايَاتُكَ الْمُفَضَّلَةُ؟",
      english: "What are your favorite hobbies?",
    },
    {
      id: "ar-m1-l8-e18",
      type: "translate",
      prompt: "translate to English",
      direction: "to-english",
      source: "فِي عُطْلَةِ نِهَايَةِ الْأُسْبُوعِ، أَلْعَبُ كُرَةَ الْقَدَمِ مَعَ أَصْدِقَائِي.",
      answer: "On the weekend, I play soccer with my friends.",
      transliteration: "fī ʿuṭlat nihāyat al-usbūʿ, alʿab kurat al-qadam maʿa aṣdiqāʾī.",
      term: { target: "أَلْعَبُ", transliteration: "alʿab", english: "I play" },
    },
    {
      id: "ar-m1-l8-e19",
      type: "explain",
      prompt:
        "talk about today's weather and your favorite hobby, in Arabic (two or three sentences) — good small talk for a new friend",
      topic: "today's weather, plus a hobby you love and when you do it",
      targetLanguageHint: "الطَّقْسُ.../هِوَايَتِي الْمُفَضَّلَةُ.../أُحِبُّ أَنْ...",
      modelAnswer: "الطَّقْسُ جَمِيل الْيَوْمَ. هِوَايَتِي الْمُفَضَّلَةُ هِيَ السِّبَاحَة، وَأَنَا أُحِبُّ أَنْ أَسْبَحَ فِي الصَّيْفِ.",
      modelAnswerEnglish: "The weather is nice today. My favorite hobby is swimming, and I love to swim in summer.",
    },
  ],
};

export const arLessons: Lesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
  lesson5,
  lesson6,
  lesson7,
  lesson8,
];

export const arModules = buildModules(
  "ar",
  arLessons.map((l) => l.id)
);

// ---------- Quote bank ----------
// 8 short quotes/verses native to the Arabic tradition — the Qur'an, an
// authentic hadith, Ibn Khaldun's Muqaddimah, classical poetry, and a
// well-known proverb. Native Arabic text carries full tashkeel (these are
// short, fixed, canonically-vocalized texts); wording follows widely
// published standard renderings.
export const arQuotes: Quote[] = [
  {
    id: "ar-q1",
    language: "ar",
    native: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا، إِنَّ مَعَ الْعُسْرِ يُسْرًا.",
    transliteration: "fa-inna maʿa al-ʿusri yusrā, inna maʿa al-ʿusri yusrā.",
    english: "So, indeed, with hardship comes ease; indeed, with hardship comes ease.",
    source: "Qur'an 94:5-6",
    author: "The Qur'an, Surah Ash-Sharh",
  },
  {
    id: "ar-q2",
    language: "ar",
    native: "وَقُلْ رَبِّ زِدْنِي عِلْمًا.",
    transliteration: "wa-qul rabbi zidnī ʿilmā.",
    english: "And say: My Lord, increase me in knowledge.",
    source: "Qur'an 20:114",
    author: "The Qur'an, Surah Ta-Ha",
  },
  {
    id: "ar-q3",
    language: "ar",
    native: "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّى يُغَيِّرُوا مَا بِأَنْفُسِهِمْ.",
    transliteration: "inna Allāha lā yughayyiru mā bi-qawmin ḥattā yughayyirū mā bi-anfusihim.",
    english: "Indeed, Allah will not change the condition of a people until they change what is in themselves.",
    source: "Qur'an 13:11",
    author: "The Qur'an, Surah Ar-Ra'd",
  },
  {
    id: "ar-q4",
    language: "ar",
    native: "هَلْ جَزَاءُ الْإِحْسَانِ إِلَّا الْإِحْسَانُ؟",
    transliteration: "hal jazāʾu al-iḥsāni illā al-iḥsān?",
    english: "Is the reward of goodness anything but goodness?",
    source: "Qur'an 55:60",
    author: "The Qur'an, Surah Ar-Rahman",
  },
  {
    id: "ar-q5",
    language: "ar",
    native: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ.",
    transliteration: "ṭalabu al-ʿilmi farīḍatun ʿalā kulli muslim.",
    english: "Seeking knowledge is an obligation upon every Muslim.",
    source: "Hadith, Sunan Ibn Majah",
    author: "Attributed to the Prophet Muhammad",
  },
  {
    id: "ar-q6",
    language: "ar",
    native: "الظُّلْمُ مُؤْذِنٌ بِخَرَابِ الْعُمْرَانِ.",
    transliteration: "aẓ-ẓulmu muʾdhinun bi-kharābi al-ʿumrān.",
    english: "Injustice heralds the ruin of civilization.",
    source: "Al-Muqaddimah",
    author: "Ibn Khaldun",
  },
  {
    id: "ar-q7",
    language: "ar",
    native: "عَلَى قَدْرِ أَهْلِ الْعَزْمِ تَأْتِي الْعَزَائِمُ.",
    transliteration: "ʿalā qadri ahli al-ʿazmi taʾtī al-ʿazāʾim.",
    english: "Resolve arrives in proportion to the resolve of those who hold it.",
    source: "Diwan al-Mutanabbi",
    author: "Al-Mutanabbi",
  },
  {
    id: "ar-q8",
    language: "ar",
    native: "الصَّدِيقُ وَقْتَ الضِّيقِ.",
    transliteration: "aṣ-ṣadīqu waqta aḍ-ḍīq.",
    english: "A true friend is known in times of hardship.",
    source: "Traditional Arabic proverb",
  },
];
