import type { Lesson, Quote } from "../types";
import { buildModules } from "./moduleDefs";

// ---------- Module 1 core lessons ----------
// Schema reference lesson for the whole betterD content set — Chinese and
// Arabic authors should match this shape exactly, translated conceptually
// (not literally) into their own language, vocabulary, and cultural context.

const lesson1: Lesson = {
  id: "es-m1-l1",
  moduleId: "es-m1",
  language: "es",
  title: "greetings & introductions",
  size: "small",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l1-e1",
      type: "match",
      prompt: "match each greeting to its meaning",
      pairs: [
        { target: "Hola", english: "Hello" },
        { target: "Buenos días", english: "Good morning" },
        { target: "Buenas tardes", english: "Good afternoon" },
        { target: "Buenas noches", english: "Good night" },
        { target: "Adiós", english: "Goodbye" },
      ],
    },
    {
      id: "es-m1-l1-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "Hello, nice to meet you.",
      answer: "Hola, mucho gusto.",
      term: { target: "mucho gusto", english: "nice to meet you" },
    },
    {
      id: "es-m1-l1-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "¿Cómo te llamas?",
      answer: "What is your name?",
      term: { target: "¿Cómo te llamas?", english: "What is your name?" },
    },
    {
      id: "es-m1-l1-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Buenos días, ¿cómo ___?",
      english: "Good morning, how are you?",
      answer: "estás",
      options: ["estás", "estoy", "está", "eres"],
      term: { target: "¿Cómo estás?", english: "How are you?" },
    },
    {
      id: "es-m1-l1-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "Me llamo Ana. Mucho gusto.",
      english: "My name is Ana. Nice to meet you.",
      term: { target: "Me llamo...", english: "My name is..." },
    },
    {
      id: "es-m1-l1-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "Buenas tardes. ¿Cómo estás?",
      question: "What time of day is being greeted?",
      options: ["Morning", "Afternoon", "Night"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l1-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "What is your name?",
      words: ["¿Cómo", "te", "llamas?"],
    },
    {
      id: "es-m1-l1-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "Hasta luego.",
      english: "See you later.",
    },
    {
      id: "es-m1-l1-e9",
      type: "explain",
      prompt: "introduce yourself in one sentence, in spanish only",
      topic: "your name and that you're happy to meet someone",
      targetLanguageHint: "Me llamo ___.",
      modelAnswer: "Me llamo Ana. Mucho gusto en conocerte.",
      modelAnswerEnglish: "My name is Ana. Nice to meet you.",
    },
  ],
};

const lesson2: Lesson = {
  id: "es-m1-l2",
  moduleId: "es-m1",
  language: "es",
  title: "numbers, colors & basic descriptions",
  size: "small",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l2-e1",
      type: "match",
      prompt: "match each number to its word",
      pairs: [
        { target: "uno", english: "one" },
        { target: "dos", english: "two" },
        { target: "tres", english: "three" },
        { target: "cuatro", english: "four" },
        { target: "cinco", english: "five" },
      ],
    },
    {
      id: "es-m1-l2-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "The car is red.",
      answer: "El carro es rojo.",
      term: { target: "rojo", english: "red" },
    },
    {
      id: "es-m1-l2-e3",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "El cielo es ___.",
      english: "The sky is blue.",
      answer: "azul",
      options: ["azul", "rojo", "verde", "negro"],
      term: { target: "azul", english: "blue" },
    },
    {
      id: "es-m1-l2-e4",
      type: "speak",
      prompt: "say this aloud",
      target: "La casa es grande y bonita.",
      english: "The house is big and pretty.",
      term: { target: "grande", english: "big" },
    },
    {
      id: "es-m1-l2-e5",
      type: "listen",
      prompt: "listen and answer",
      audioText: "Tengo tres gatos negros.",
      question: "How many cats does the speaker have?",
      options: ["Two", "Three", "Four"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l2-e6",
      type: "reorder",
      prompt: "put the words in order",
      english: "The house is small.",
      words: ["La", "casa", "es", "pequeña."],
    },
    {
      id: "es-m1-l2-e7",
      type: "dictation",
      prompt: "type what you hear",
      target: "El libro es verde.",
      english: "The book is green.",
    },
    {
      id: "es-m1-l2-e8",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "¿Cuántos años tienes?",
      answer: "How old are you?",
      term: { target: "¿Cuántos años tienes?", english: "How old are you?" },
    },
    {
      id: "es-m1-l2-e9",
      type: "explain",
      prompt: "describe an object you own, in spanish only",
      topic: "an object you own, using a color and a size adjective",
      targetLanguageHint: "Mi ___ es ___ y ___.",
      modelAnswer: "Mi mochila es azul y pequeña.",
      modelAnswerEnglish: "My backpack is blue and small.",
    },
  ],
};

const lesson3: Lesson = {
  id: "es-m1-l3",
  moduleId: "es-m1",
  language: "es",
  title: "family & people",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l3-e1",
      type: "match",
      prompt: "match each family word to its meaning",
      pairs: [
        { target: "el padre", english: "father" },
        { target: "la madre", english: "mother" },
        { target: "el hermano", english: "brother" },
        { target: "la hermana", english: "sister" },
        { target: "el abuelo", english: "grandfather" },
        { target: "la abuela", english: "grandmother" },
      ],
    },
    {
      id: "es-m1-l3-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "This is my mother.",
      answer: "Esta es mi madre.",
      term: { target: "la madre", english: "mother" },
    },
    {
      id: "es-m1-l3-e3",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "I have two brothers and one sister.",
      answer: "Tengo dos hermanos y una hermana.",
      term: { target: "el hermano", english: "brother" },
    },
    {
      id: "es-m1-l3-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Mi ___ se llama Carlos.",
      english: "My father is named Carlos.",
      answer: "padre",
      options: ["padre", "madre", "hermana", "abuela"],
      term: { target: "el padre", english: "father" },
    },
    {
      id: "es-m1-l3-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "Mi abuela es muy amable.",
      english: "My grandmother is very kind.",
      term: { target: "amable", english: "kind" },
    },
    {
      id: "es-m1-l3-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "Tengo una hermana mayor y un hermano menor.",
      question: "How many siblings does the speaker have in total?",
      options: ["One", "Two", "Three"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l3-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "My family is big.",
      words: ["Mi", "familia", "es", "grande."],
    },
    {
      id: "es-m1-l3-e8",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "¿Cuántos hermanos tienes?",
      answer: "How many siblings do you have?",
      term: { target: "¿Cuántos hermanos tienes?", english: "How many siblings do you have?" },
    },
    {
      id: "es-m1-l3-e9",
      type: "dictation",
      prompt: "type what you hear",
      target: "Ella es mi esposa.",
      english: "She is my wife.",
    },
    {
      id: "es-m1-l3-e10",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "___ padres viven en México.",
      english: "My parents live in Mexico.",
      answer: "Mis",
      options: ["Mis", "Mi", "Su", "Tus"],
      term: { target: "mis", english: "my (plural)" },
    },
    {
      id: "es-m1-l3-e11",
      type: "match",
      prompt: "match each word to its meaning",
      pairs: [
        { target: "alto", english: "tall" },
        { target: "bajo", english: "short" },
        { target: "joven", english: "young" },
        { target: "mayor", english: "older" },
        { target: "simpático", english: "nice, friendly" },
      ],
    },
    {
      id: "es-m1-l3-e12",
      type: "explain",
      prompt: "describe your family, in spanish only",
      topic: "the size of your family and one member of it",
      targetLanguageHint: "Mi familia es ___. Tengo ___.",
      modelAnswer: "Mi familia es pequeña. Tengo un hermano y una hermana.",
      modelAnswerEnglish: "My family is small. I have one brother and one sister.",
    },
    {
      id: "es-m1-l3-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "Mi hermano es alto y simpático.",
      english: "My brother is tall and nice.",
      term: { target: "simpático", english: "nice, friendly" },
    },
    {
      id: "es-m1-l3-e14",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "Our grandparents are older.",
      answer: "Nuestros abuelos son mayores.",
      term: { target: "nuestro", english: "our" },
    },
  ],
};

const lesson4: Lesson = {
  id: "es-m1-l4",
  moduleId: "es-m1",
  language: "es",
  title: "daily routine & time",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l4-e1",
      type: "match",
      prompt: "match each verb to its meaning",
      pairs: [
        { target: "levantarse", english: "to get up" },
        { target: "ducharse", english: "to shower" },
        { target: "vestirse", english: "to get dressed" },
        { target: "acostarse", english: "to go to bed" },
        { target: "desayunar", english: "to have breakfast" },
      ],
    },
    {
      id: "es-m1-l4-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "I wake up at seven.",
      answer: "Me levanto a las siete.",
      term: { target: "levantarse", english: "to get up (reflexive)" },
    },
    {
      id: "es-m1-l4-e3",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "¿Qué hora ___?",
      english: "What time is it?",
      answer: "es",
      options: ["es", "son", "está", "eres"],
      term: { target: "¿Qué hora es?", english: "What time is it?" },
    },
    {
      id: "es-m1-l4-e4",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "Son las tres de la tarde.",
      answer: "It's three in the afternoon.",
      term: { target: "Son las...", english: "It is... (time, plural hours)" },
    },
    {
      id: "es-m1-l4-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "Me ducho y luego desayuno.",
      english: "I shower and then I have breakfast.",
      term: { target: "luego", english: "then, afterward" },
    },
    {
      id: "es-m1-l4-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "Trabajo todos los días excepto el domingo.",
      question: "Which day does the speaker NOT work?",
      options: ["Saturday", "Sunday", "Monday"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l4-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "I go to bed at ten.",
      words: ["Me", "acuesto", "a", "las", "diez."],
    },
    {
      id: "es-m1-l4-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "Estudio por la noche.",
      english: "I study at night.",
    },
    {
      id: "es-m1-l4-e9",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Ella ___ viste rápido.",
      english: "She gets dressed quickly.",
      answer: "se",
      options: ["se", "me", "te", "nos"],
      term: { target: "vestirse", english: "to get dressed" },
    },
    {
      id: "es-m1-l4-e10",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "We always eat dinner at eight.",
      answer: "Siempre cenamos a las ocho.",
      term: { target: "siempre", english: "always" },
    },
    {
      id: "es-m1-l4-e11",
      type: "explain",
      prompt: "describe your morning routine, in spanish only",
      topic: "your morning routine, using two actions in order",
      targetLanguageHint: "Me levanto a las ___. Luego ___.",
      modelAnswer: "Me levanto a las siete. Luego me ducho y desayuno.",
      modelAnswerEnglish: "I get up at seven. Then I shower and have breakfast.",
    },
    {
      id: "es-m1-l4-e12",
      type: "match",
      prompt: "match each expression to its meaning",
      pairs: [
        { target: "siempre", english: "always" },
        { target: "a veces", english: "sometimes" },
        { target: "nunca", english: "never" },
        { target: "todos los días", english: "every day" },
      ],
    },
    {
      id: "es-m1-l4-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "A veces trabajo los fines de semana.",
      english: "Sometimes I work on weekends.",
      term: { target: "a veces", english: "sometimes" },
    },
  ],
};

const lesson5: Lesson = {
  id: "es-m1-l5",
  moduleId: "es-m1",
  language: "es",
  title: "food & dining",
  size: "large",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l5-e1",
      type: "match",
      prompt: "match each food to its meaning",
      pairs: [
        { target: "el pan", english: "bread" },
        { target: "el agua", english: "water" },
        { target: "la carne", english: "meat" },
        { target: "el pollo", english: "chicken" },
        { target: "el arroz", english: "rice" },
        { target: "la fruta", english: "fruit" },
      ],
    },
    {
      id: "es-m1-l5-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "I would like a coffee, please.",
      answer: "Quisiera un café, por favor.",
      term: { target: "quisiera", english: "I would like" },
    },
    {
      id: "es-m1-l5-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "¿Qué recomienda usted?",
      answer: "What do you recommend?",
      term: { target: "¿Qué recomienda?", english: "What do you recommend?" },
    },
    {
      id: "es-m1-l5-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Yo ___ pollo con arroz.",
      english: "I eat chicken with rice.",
      answer: "como",
      options: ["como", "bebo", "quiero", "pido"],
      term: { target: "comer", english: "to eat" },
    },
    {
      id: "es-m1-l5-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "La sopa está muy caliente.",
      english: "The soup is very hot.",
      term: { target: "caliente", english: "hot (temperature)" },
    },
    {
      id: "es-m1-l5-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "¿Me trae la cuenta, por favor?",
      question: "What is being requested?",
      options: ["The menu", "The bill", "A napkin"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l5-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "I want a glass of water.",
      words: ["Quiero", "un", "vaso", "de", "agua."],
    },
    {
      id: "es-m1-l5-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "El postre está delicioso.",
      english: "The dessert is delicious.",
    },
    {
      id: "es-m1-l5-e9",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Tenemos una reserva ___ dos personas.",
      english: "We have a reservation for two people.",
      answer: "para",
      options: ["para", "por", "de", "con"],
      term: { target: "para", english: "for" },
    },
    {
      id: "es-m1-l5-e10",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "The food is spicy.",
      answer: "La comida está picante.",
      term: { target: "picante", english: "spicy" },
    },
    {
      id: "es-m1-l5-e11",
      type: "match",
      prompt: "match each verb to its meaning",
      pairs: [
        { target: "pedir", english: "to order, to ask for" },
        { target: "beber", english: "to drink" },
        { target: "cocinar", english: "to cook" },
        { target: "probar", english: "to try, to taste" },
      ],
    },
    {
      id: "es-m1-l5-e12",
      type: "explain",
      prompt: "order food at a restaurant, in spanish only",
      topic: "ordering a dish and a drink at a restaurant",
      targetLanguageHint: "Quisiera ___ y ___, por favor.",
      modelAnswer: "Quisiera el pollo con arroz y un jugo de naranja, por favor.",
      modelAnswerEnglish: "I would like the chicken with rice and an orange juice, please.",
    },
    {
      id: "es-m1-l5-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "¿Está incluida la propina?",
      english: "Is the tip included?",
      term: { target: "la propina", english: "the tip" },
    },
    {
      id: "es-m1-l5-e14",
      type: "listen",
      prompt: "listen and answer",
      audioText: "Voy a pedir el pescado con verduras.",
      question: "What is being ordered?",
      options: ["Chicken with rice", "Fish with vegetables", "Soup with bread"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l5-e15",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "Soy alérgico a los mariscos.",
      answer: "I am allergic to seafood.",
      term: { target: "alérgico/a a", english: "allergic to" },
    },
    {
      id: "es-m1-l5-e16",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Nosotros ___ mucha hambre.",
      english: "We are very hungry.",
      answer: "tenemos",
      options: ["tenemos", "somos", "estamos", "hacemos"],
      term: { target: "tener hambre", english: "to be hungry" },
    },
    {
      id: "es-m1-l5-e17",
      type: "reorder",
      prompt: "put the words in order",
      english: "The restaurant is very good.",
      words: ["El", "restaurante", "es", "muy", "bueno."],
    },
    {
      id: "es-m1-l5-e18",
      type: "dictation",
      prompt: "type what you hear",
      target: "¿Aceptan tarjeta de crédito?",
      english: "Do you accept credit cards?",
    },
    {
      id: "es-m1-l5-e19",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "Can I have the menu, please?",
      answer: "¿Me trae el menú, por favor?",
      term: { target: "el menú", english: "the menu" },
    },
  ],
};

const lesson6: Lesson = {
  id: "es-m1-l6",
  moduleId: "es-m1",
  language: "es",
  title: "home & directions",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l6-e1",
      type: "match",
      prompt: "match each room to its meaning",
      pairs: [
        { target: "la cocina", english: "kitchen" },
        { target: "el baño", english: "bathroom" },
        { target: "el dormitorio", english: "bedroom" },
        { target: "la sala", english: "living room" },
        { target: "el jardín", english: "garden" },
      ],
    },
    {
      id: "es-m1-l6-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "The kitchen is next to the living room.",
      answer: "La cocina está al lado de la sala.",
      term: { target: "al lado de", english: "next to" },
    },
    {
      id: "es-m1-l6-e3",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Mi casa está ___ del parque.",
      english: "My house is near the park.",
      answer: "cerca",
      options: ["cerca", "lejos", "entre", "sobre"],
      term: { target: "cerca de", english: "near" },
    },
    {
      id: "es-m1-l6-e4",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "Sigue todo recto y dobla a la izquierda.",
      answer: "Go straight and turn left.",
      term: { target: "a la izquierda", english: "to the left" },
    },
    {
      id: "es-m1-l6-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "Gira a la derecha en la esquina.",
      english: "Turn right at the corner.",
      term: { target: "a la derecha", english: "to the right" },
    },
    {
      id: "es-m1-l6-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "El banco está enfrente de la farmacia.",
      question: "Where is the bank?",
      options: ["Next to the pharmacy", "Across from the pharmacy", "Far from the pharmacy"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l6-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "The bedroom is upstairs.",
      words: ["El", "dormitorio", "está", "arriba."],
    },
    {
      id: "es-m1-l6-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "¿Dónde está el baño?",
      english: "Where is the bathroom?",
    },
    {
      id: "es-m1-l6-e9",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Madrid ___ en España.",
      english: "Madrid is in Spain.",
      answer: "está",
      options: ["está", "es", "hay", "son"],
      term: { target: "estar", english: "to be (location, state)" },
    },
    {
      id: "es-m1-l6-e10",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "The house is between the park and the school.",
      answer: "La casa está entre el parque y la escuela.",
      term: { target: "entre", english: "between" },
    },
    {
      id: "es-m1-l6-e11",
      type: "explain",
      prompt: "give directions to your house, in spanish only",
      topic: "directions from a nearby landmark to your house",
      targetLanguageHint: "Mi casa está ___ de ___.",
      modelAnswer: "Mi casa está cerca de la estación. Sigue todo recto y dobla a la derecha.",
      modelAnswerEnglish: "My house is near the station. Go straight and turn right.",
    },
    {
      id: "es-m1-l6-e12",
      type: "match",
      prompt: "match each verb to its meaning",
      pairs: [
        { target: "doblar", english: "to turn" },
        { target: "seguir", english: "to continue, to follow" },
        { target: "cruzar", english: "to cross" },
        { target: "subir", english: "to go up" },
      ],
    },
    {
      id: "es-m1-l6-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "Hay un parque enfrente de mi casa.",
      english: "There is a park across from my house.",
      term: { target: "hay", english: "there is, there are" },
    },
  ],
};

const lesson7: Lesson = {
  id: "es-m1-l7",
  moduleId: "es-m1",
  language: "es",
  title: "shopping & money",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l7-e1",
      type: "match",
      prompt: "match each item to its meaning",
      pairs: [
        { target: "la camisa", english: "shirt" },
        { target: "los zapatos", english: "shoes" },
        { target: "el vestido", english: "dress" },
        { target: "los pantalones", english: "pants" },
        { target: "la chaqueta", english: "jacket" },
      ],
    },
    {
      id: "es-m1-l7-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "How much does this cost?",
      answer: "¿Cuánto cuesta esto?",
      term: { target: "¿Cuánto cuesta?", english: "How much does it cost?" },
    },
    {
      id: "es-m1-l7-e3",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Esta camisa es muy ___.",
      english: "This shirt is very expensive.",
      answer: "cara",
      options: ["cara", "caro", "barata", "barato"],
      term: { target: "caro/a", english: "expensive" },
    },
    {
      id: "es-m1-l7-e4",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "¿Tiene esto en talla mediana?",
      answer: "Do you have this in a medium size?",
      term: { target: "la talla", english: "size (clothing)" },
    },
    {
      id: "es-m1-l7-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "Quisiera probarme estos zapatos.",
      english: "I would like to try on these shoes.",
      term: { target: "probarse", english: "to try on" },
    },
    {
      id: "es-m1-l7-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "La chaqueta cuesta cuarenta dólares.",
      question: "How much does the jacket cost?",
      options: ["Fourteen dollars", "Forty dollars", "Four dollars"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l7-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "Where can I pay?",
      words: ["¿Dónde", "puedo", "pagar?"],
    },
    {
      id: "es-m1-l7-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "¿Aceptan efectivo?",
      english: "Do you accept cash?",
    },
    {
      id: "es-m1-l7-e9",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "¿Puedo pagar ___ tarjeta?",
      english: "Can I pay with card?",
      answer: "con",
      options: ["con", "por", "para", "de"],
      term: { target: "con tarjeta", english: "with card" },
    },
    {
      id: "es-m1-l7-e10",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "This store is very cheap.",
      answer: "Esta tienda es muy barata.",
      term: { target: "barato/a", english: "cheap" },
    },
    {
      id: "es-m1-l7-e11",
      type: "explain",
      prompt: "ask about a price and a size while shopping, in spanish only",
      topic: "asking the price of an item and whether it comes in your size",
      targetLanguageHint: "¿Cuánto cuesta ___? ¿Tiene talla ___?",
      modelAnswer: "¿Cuánto cuesta este vestido? ¿Tiene talla mediana?",
      modelAnswerEnglish: "How much does this dress cost? Do you have a medium size?",
    },
    {
      id: "es-m1-l7-e12",
      type: "match",
      prompt: "match each number to its word",
      pairs: [
        { target: "veinte", english: "twenty" },
        { target: "treinta", english: "thirty" },
        { target: "cuarenta", english: "forty" },
        { target: "cincuenta", english: "fifty" },
        { target: "cien", english: "one hundred" },
      ],
    },
    {
      id: "es-m1-l7-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "El total es setenta y cinco dólares.",
      english: "The total is seventy-five dollars.",
      term: { target: "el total", english: "the total" },
    },
  ],
};

const lesson8: Lesson = {
  id: "es-m1-l8",
  moduleId: "es-m1",
  language: "es",
  title: "weather, small talk & hobbies bridge",
  size: "large",
  kind: "core",
  exercises: [
    {
      id: "es-m1-l8-e1",
      type: "match",
      prompt: "match each expression to its meaning",
      pairs: [
        { target: "hace sol", english: "it's sunny" },
        { target: "hace frío", english: "it's cold" },
        { target: "hace calor", english: "it's hot" },
        { target: "llueve", english: "it's raining" },
        { target: "nieva", english: "it's snowing" },
      ],
    },
    {
      id: "es-m1-l8-e2",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "It's sunny today.",
      answer: "Hoy hace sol.",
      term: { target: "hace sol", english: "it's sunny" },
    },
    {
      id: "es-m1-l8-e3",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "En invierno ___ mucho frío.",
      english: "In winter it's very cold.",
      answer: "hace",
      options: ["hace", "es", "está", "tiene"],
      term: { target: "hace frío", english: "it's cold" },
    },
    {
      id: "es-m1-l8-e4",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "Está lloviendo mucho hoy.",
      answer: "It's raining a lot today.",
      term: { target: "llover", english: "to rain" },
    },
    {
      id: "es-m1-l8-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "Me gusta caminar cuando hace buen tiempo.",
      english: "I like to walk when the weather is nice.",
      term: { target: "me gusta", english: "I like" },
    },
    {
      id: "es-m1-l8-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "Mañana va a nevar en las montañas.",
      question: "What is the weather forecast?",
      options: ["Rain", "Snow", "Sun"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l8-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "I like to read books.",
      words: ["Me", "gusta", "leer", "libros."],
    },
    {
      id: "es-m1-l8-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "¿Qué tal tu día?",
      english: "How was your day?",
    },
    {
      id: "es-m1-l8-e9",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "Nos ___ los deportes.",
      english: "We like sports.",
      answer: "gustan",
      options: ["gustan", "gusta", "gustamos", "gustar"],
      term: { target: "gustar (plural)", english: "to be pleasing (plural)" },
    },
    {
      id: "es-m1-l8-e10",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "I like to swim and dance.",
      answer: "Me gusta nadar y bailar.",
      term: { target: "nadar", english: "to swim" },
    },
    {
      id: "es-m1-l8-e11",
      type: "explain",
      prompt: "talk about your hobbies, in spanish only",
      topic: "two activities you like to do in your free time",
      targetLanguageHint: "Me gusta ___ y ___.",
      modelAnswer: "Me gusta jugar al fútbol y ver películas los fines de semana.",
      modelAnswerEnglish: "I like to play soccer and watch movies on weekends.",
    },
    {
      id: "es-m1-l8-e12",
      type: "match",
      prompt: "match each verb to its meaning",
      pairs: [
        { target: "leer", english: "to read" },
        { target: "bailar", english: "to dance" },
        { target: "jugar", english: "to play" },
        { target: "cocinar", english: "to cook" },
      ],
    },
    {
      id: "es-m1-l8-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "¿Qué te gusta hacer los fines de semana?",
      english: "What do you like to do on weekends?",
      term: { target: "los fines de semana", english: "on weekends" },
    },
    {
      id: "es-m1-l8-e14",
      type: "listen",
      prompt: "listen and answer",
      audioText: "A ella le gusta escuchar música y bailar salsa.",
      question: "What does she like to do?",
      options: ["Play soccer and read", "Listen to music and dance salsa", "Cook and swim"],
      correctIndex: 1,
    },
    {
      id: "es-m1-l8-e15",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "No me gusta el frío.",
      answer: "I don't like the cold.",
      term: { target: "no me gusta", english: "I don't like" },
    },
    {
      id: "es-m1-l8-e16",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "A mi hermano le ___ jugar al fútbol.",
      english: "My brother likes to play soccer.",
      answer: "gusta",
      options: ["gusta", "gustan", "gusto", "gustas"],
      term: { target: "a él le gusta", english: "he likes" },
    },
    {
      id: "es-m1-l8-e17",
      type: "reorder",
      prompt: "put the words in order",
      english: "It's cloudy and cold today.",
      words: ["Hoy", "está", "nublado", "y", "hace", "frío."],
    },
    {
      id: "es-m1-l8-e18",
      type: "dictation",
      prompt: "type what you hear",
      target: "Me gusta mucho la música clásica.",
      english: "I like classical music a lot.",
    },
    {
      id: "es-m1-l8-e19",
      type: "translate",
      prompt: "translate to spanish",
      direction: "to-target",
      source: "What's the weather like today?",
      answer: "¿Qué tiempo hace hoy?",
      term: { target: "¿Qué tiempo hace?", english: "What's the weather like?" },
    },
    {
      id: "es-m1-l8-e20",
      type: "speak",
      prompt: "say this aloud",
      target: "En verano hace mucho calor y en invierno hace frío.",
      english: "In summer it's very hot and in winter it's cold.",
      term: { target: "el verano", english: "summer" },
    },
  ],
};

export const esLessons: Lesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
  lesson5,
  lesson6,
  lesson7,
  lesson8,
];

export const esModules = buildModules(
  "es",
  esLessons.map((l) => l.id)
);

export const esQuotes: Quote[] = [
  {
    id: "es-q1",
    language: "es",
    native:
      "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",
    english: "Freedom, Sancho, is one of the most precious gifts that heaven gave to man.",
    source: "Don Quijote de la Mancha, Parte II, Cap. 58",
    author: "Miguel de Cervantes",
  },
  {
    id: "es-q2",
    language: "es",
    native: "Puedo escribir los versos más tristes esta noche.",
    english: "Tonight I can write the saddest lines.",
    source: "Veinte poemas de amor y una canción desesperada, Poema 20",
    author: "Pablo Neruda",
  },
  {
    id: "es-q3",
    language: "es",
    native: "Yo, que me figuraba el Paraíso bajo la especie de una biblioteca.",
    english: "I, who always pictured Paradise as a kind of library.",
    source: "Poema de los dones, El hacedor",
    author: "Jorge Luis Borges",
  },
  {
    id: "es-q4",
    language: "es",
    native:
      "Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",
    english:
      "Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon when his father took him to discover ice.",
    source: "Cien años de soledad, primera línea",
    author: "Gabriel García Márquez",
  },
  {
    id: "es-q5",
    language: "es",
    native: "La fe que no duda es fe muerta.",
    english: "Faith that does not doubt is dead faith.",
    source: "Del sentimiento trágico de la vida",
    author: "Miguel de Unamuno",
  },
  {
    id: "es-q6",
    language: "es",
    native:
      "Hombres necios que acusáis a la mujer sin razón, sin ver que sois la ocasión de lo mismo que culpáis.",
    english:
      "Foolish men who accuse women without reason, not seeing that you are the cause of the very thing you blame.",
    source: "Hombres necios (Redondillas)",
    author: "Sor Juana Inés de la Cruz",
  },
  {
    id: "es-q7",
    language: "es",
    native: "Verde que te quiero verde.",
    english: "Green, how I want you green.",
    source: "Romance sonámbulo, Romancero gitano",
    author: "Federico García Lorca",
  },
];
