import type { Lesson, Quote } from "../types";
import { buildModules } from "./moduleDefs";

// ---------- Module 1 core lessons ----------

const lesson1: Lesson = {
  id: "zh-m1-l1",
  moduleId: "zh-m1",
  language: "zh",
  title: "greetings & introductions",
  size: "small",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l1-e1",
      type: "match",
      prompt: "match each greeting to its meaning",
      pairs: [
        { target: "你好", transliteration: "nǐ hǎo", english: "Hello" },
        { target: "早上好", transliteration: "zǎoshang hǎo", english: "Good morning" },
        { target: "晚上好", transliteration: "wǎnshang hǎo", english: "Good evening" },
        { target: "再見", transliteration: "zàijiàn", simplified: "再见", english: "Goodbye" },
        { target: "謝謝", transliteration: "xièxie", simplified: "谢谢", english: "Thank you" },
      ],
    },
    {
      id: "zh-m1-l1-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "Hello, nice to meet you.",
      answer: "你好，很高興認識你。",
      transliteration: "nǐ hǎo, hěn gāoxìng rènshi nǐ.",
      term: { target: "很高兴认识你", transliteration: "hěn gāoxìng rènshi nǐ", english: "nice to meet you" },
    },
    {
      id: "zh-m1-l1-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "你叫什麼名字？",
      simplified: "你叫什么名字？",
      answer: "What is your name?",
      transliteration: "nǐ jiào shénme míngzi?",
      term: { target: "你叫什么名字？", transliteration: "nǐ jiào shénme míngzi?", english: "What is your name?" },
    },
    {
      id: "zh-m1-l1-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "你好___？",
      transliteration: "nǐ hǎo ___?",
      english: "How are you?",
      answer: "嗎",
      options: ["嗎", "呢", "吧", "啊"],
      term: { target: "吗", transliteration: "ma", english: "question particle (turns a statement into a yes/no question)" },
    },
    {
      id: "zh-m1-l1-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "我叫安娜，很高興認識你。",
      simplified: "我叫安娜，很高兴认识你。",
      transliteration: "wǒ jiào Ānnà, hěn gāoxìng rènshi nǐ.",
      english: "My name is Ana, nice to meet you.",
      term: { target: "我叫...", transliteration: "wǒ jiào...", english: "my name is..." },
    },
    {
      id: "zh-m1-l1-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "晚上好，你好嗎？",
      question: "What time of day is being greeted?",
      options: ["Morning", "Afternoon", "Evening"],
      correctIndex: 2,
    },
    {
      id: "zh-m1-l1-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "What is your name?",
      words: ["你", "叫", "什麼", "名字"],
    },
    {
      id: "zh-m1-l1-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "謝謝你，再見。",
      english: "Thank you, goodbye.",
    },
    {
      id: "zh-m1-l1-e9",
      type: "explain",
      prompt: "introduce yourself in one sentence, in chinese only",
      topic: "your name and that you're happy to meet someone",
      targetLanguageHint: "我叫___。",
      modelAnswer: "我叫安娜，很高興認識你。",
      modelAnswerEnglish: "My name is Ana, nice to meet you.",
    },
  ],
};

const lesson2: Lesson = {
  id: "zh-m1-l2",
  moduleId: "zh-m1",
  language: "zh",
  title: "numbers, colors & basic descriptions",
  size: "small",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l2-e1",
      type: "match",
      prompt: "match each number to its meaning",
      pairs: [
        { target: "一", transliteration: "yī", english: "one" },
        { target: "二", transliteration: "èr", english: "two" },
        { target: "三", transliteration: "sān", english: "three" },
        { target: "四", transliteration: "sì", english: "four" },
        { target: "五", transliteration: "wǔ", english: "five" },
      ],
    },
    {
      id: "zh-m1-l2-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I have three books.",
      answer: "我有三本書。",
      transliteration: "wǒ yǒu sān běn shū.",
      term: { target: "本", transliteration: "běn", english: "measure word for books" },
    },
    {
      id: "zh-m1-l2-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "我的貓是白色的。",
      simplified: "我的猫是白色的。",
      answer: "My cat is white.",
      transliteration: "wǒ de māo shì báisè de.",
      term: { target: "白色", transliteration: "báisè", english: "white" },
    },
    {
      id: "zh-m1-l2-e4",
      type: "speak",
      prompt: "say this aloud",
      target: "我喜歡紅色。",
      simplified: "我喜欢红色。",
      transliteration: "wǒ xǐhuan hóngsè.",
      english: "I like red.",
      term: { target: "喜欢", transliteration: "xǐhuan", english: "to like" },
    },
    {
      id: "zh-m1-l2-e5",
      type: "listen",
      prompt: "listen and answer",
      audioText: "我有五本紅色的書。",
      question: "How many books does the speaker have?",
      options: ["Three", "Four", "Five"],
      correctIndex: 2,
    },
    {
      id: "zh-m1-l2-e6",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "他有___只狗。",
      transliteration: "tā yǒu ___ zhī gǒu.",
      english: "He has two dogs.",
      answer: "兩",
      options: ["兩", "二", "三", "四"],
      term: { target: "两", transliteration: "liǎng", english: "two (used before a measure word, instead of 二)" },
    },
    {
      id: "zh-m1-l2-e7",
      type: "reorder",
      prompt: "put the words in order",
      english: "I really like blue.",
      words: ["我", "很", "喜歡", "藍色"],
    },
    {
      id: "zh-m1-l2-e8",
      type: "dictation",
      prompt: "type what you hear",
      target: "這是綠色的。",
      english: "This is green.",
    },
    {
      id: "zh-m1-l2-e9",
      type: "explain",
      prompt: "describe something you own, in chinese only",
      topic: "describe an object's color and size using 大/小",
      targetLanguageHint: "我的___是___色的，很___。",
      modelAnswer: "我的書包是藍色的，很大。",
      modelAnswerEnglish: "My backpack is blue, it's very big.",
    },
  ],
};

const lesson3: Lesson = {
  id: "zh-m1-l3",
  moduleId: "zh-m1",
  language: "zh",
  title: "family & people",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l3-e1",
      type: "match",
      prompt: "match each family word to its meaning",
      pairs: [
        { target: "爸爸", transliteration: "bàba", english: "dad" },
        { target: "媽媽", transliteration: "māma", simplified: "妈妈", english: "mom" },
        { target: "哥哥", transliteration: "gēge", english: "older brother" },
        { target: "姐姐", transliteration: "jiějie", english: "older sister" },
        { target: "朋友", transliteration: "péngyou", english: "friend" },
      ],
    },
    {
      id: "zh-m1-l3-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "This is my mother.",
      answer: "這是我的媽媽。",
      transliteration: "zhè shì wǒ de māma.",
      term: { target: "这是我的...", transliteration: "zhè shì wǒ de...", english: "this is my..." },
    },
    {
      id: "zh-m1-l3-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "他是我哥哥。",
      answer: "He is my older brother.",
      transliteration: "tā shì wǒ gēge.",
      term: { target: "哥哥", transliteration: "gēge", english: "older brother" },
    },
    {
      id: "zh-m1-l3-e4",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I have two younger sisters.",
      answer: "我有兩個妹妹。",
      transliteration: "wǒ yǒu liǎng ge mèimei.",
      term: { target: "个", transliteration: "ge", english: "general-purpose measure word" },
    },
    {
      id: "zh-m1-l3-e5",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "你家有___個人？",
      simplified: "你家有___个人？",
      transliteration: "nǐ jiā yǒu ___ ge rén?",
      english: "How many people are in your family?",
      answer: "幾",
      options: ["幾", "什麼", "誰", "多"],
      term: { target: "几", transliteration: "jǐ", english: "how many (for small, countable numbers)" },
    },
    {
      id: "zh-m1-l3-e6",
      type: "speak",
      prompt: "say this aloud",
      target: "我的爸爸今年五十歲。",
      simplified: "我的爸爸今年五十岁。",
      transliteration: "wǒ de bàba jīnnián wǔshí suì.",
      english: "My dad is fifty years old this year.",
      term: { target: "岁", transliteration: "suì", english: "years old (age)" },
    },
    {
      id: "zh-m1-l3-e7",
      type: "listen",
      prompt: "listen and answer",
      audioText: "我有一個哥哥和一個妹妹。",
      question: "How many siblings does the speaker mention?",
      options: ["One", "Two", "Three"],
      correctIndex: 1,
    },
    {
      id: "zh-m1-l3-e8",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "你今年___大？",
      transliteration: "nǐ jīnnián ___ dà?",
      english: "How old are you this year?",
      answer: "多",
      options: ["多", "幾", "誰", "什麼"],
      term: { target: "多大", transliteration: "duō dà", english: "how old (asking an adult's age)" },
    },
    {
      id: "zh-m1-l3-e9",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "這是誰？",
      simplified: "这是谁？",
      answer: "Who is this?",
      transliteration: "zhè shì shéi?",
      term: { target: "谁", transliteration: "shéi", english: "who" },
    },
    {
      id: "zh-m1-l3-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "This is my friend.",
      words: ["這", "是", "我的", "朋友"],
    },
    {
      id: "zh-m1-l3-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "我愛我的家人。",
      english: "I love my family.",
    },
    {
      id: "zh-m1-l3-e12",
      type: "match",
      prompt: "match each family word to its meaning",
      pairs: [
        { target: "兒子", transliteration: "érzi", simplified: "儿子", english: "son" },
        { target: "女兒", transliteration: "nǚ'ér", simplified: "女儿", english: "daughter" },
        { target: "丈夫", transliteration: "zhàngfu", english: "husband" },
        { target: "妻子", transliteration: "qīzi", english: "wife" },
        { target: "家人", transliteration: "jiārén", english: "family members" },
      ],
    },
    {
      id: "zh-m1-l3-e13",
      type: "explain",
      prompt: "describe your family, in chinese only",
      topic: "describe who's in your family and one detail (age or relation)",
      targetLanguageHint: "我家有...我的...今年...歲。",
      modelAnswer: "我家有四個人：爸爸、媽媽、哥哥和我。我哥哥今年二十歲。",
      modelAnswerEnglish: "There are four people in my family: dad, mom, older brother, and me. My older brother is twenty years old this year.",
    },
  ],
};

const lesson4: Lesson = {
  id: "zh-m1-l4",
  moduleId: "zh-m1",
  language: "zh",
  title: "daily routine & time",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l4-e1",
      type: "match",
      prompt: "match each time word to its meaning",
      pairs: [
        { target: "早上", transliteration: "zǎoshang", english: "morning" },
        { target: "中午", transliteration: "zhōngwǔ", english: "noon" },
        { target: "下午", transliteration: "xiàwǔ", english: "afternoon" },
        { target: "晚上", transliteration: "wǎnshang", english: "evening" },
        { target: "現在", transliteration: "xiànzài", simplified: "现在", english: "now" },
      ],
    },
    {
      id: "zh-m1-l4-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I get up at seven o'clock.",
      answer: "我七點起床。",
      transliteration: "wǒ qī diǎn qǐchuáng.",
      term: { target: "起床", transliteration: "qǐchuáng", english: "to get up" },
    },
    {
      id: "zh-m1-l4-e3",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "現在___點？",
      simplified: "现在___点？",
      transliteration: "xiànzài ___ diǎn?",
      english: "What time is it now?",
      answer: "幾",
      options: ["幾", "什麼", "誰", "多"],
      term: { target: "几点", transliteration: "jǐ diǎn", english: "what time (is it)" },
    },
    {
      id: "zh-m1-l4-e4",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "我每天八點上班。",
      simplified: "我每天八点上班。",
      answer: "I go to work at eight o'clock every day.",
      transliteration: "wǒ měitiān bā diǎn shàngbān.",
      term: { target: "每天", transliteration: "měitiān", english: "every day" },
    },
    {
      id: "zh-m1-l4-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "我先吃飯，然後上課。",
      simplified: "我先吃饭，然后上课。",
      transliteration: "wǒ xiān chīfàn, ránhòu shàngkè.",
      english: "I eat first, then go to class.",
      term: { target: "然后", transliteration: "ránhòu", english: "then, after that" },
    },
    {
      id: "zh-m1-l4-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "我晚上十點睡覺。",
      question: "What time does the speaker go to sleep?",
      options: ["8 o'clock", "9 o'clock", "10 o'clock"],
      correctIndex: 2,
    },
    {
      id: "zh-m1-l4-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "我___吃午飯。",
      simplified: "我___吃午饭。",
      transliteration: "wǒ ___ chī wǔfàn.",
      english: "I eat lunch at noon.",
      answer: "中午",
      options: ["中午", "早上", "晚上", "現在"],
      term: { target: "中午", transliteration: "zhōngwǔ", english: "noon" },
    },
    {
      id: "zh-m1-l4-e8",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "What time is it now?",
      answer: "現在幾點？",
      transliteration: "xiànzài jǐ diǎn?",
      term: { target: "现在", transliteration: "xiànzài", english: "now" },
    },
    {
      id: "zh-m1-l4-e9",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "It's seven thirty.",
      answer: "七點半。",
      transliteration: "qī diǎn bàn.",
      term: { target: "半", transliteration: "bàn", english: "half past (the hour)" },
    },
    {
      id: "zh-m1-l4-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "I go to bed at eleven every day.",
      words: ["我", "每天", "十一點", "睡覺"],
    },
    {
      id: "zh-m1-l4-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "他每天七點半起床。",
      english: "He gets up at seven thirty every day.",
    },
    {
      id: "zh-m1-l4-e12",
      type: "match",
      prompt: "match each activity to its meaning",
      pairs: [
        { target: "起床", transliteration: "qǐchuáng", english: "to get up" },
        { target: "吃飯", transliteration: "chīfàn", simplified: "吃饭", english: "to eat a meal" },
        { target: "上班", transliteration: "shàngbān", english: "to go to work" },
        { target: "上課", transliteration: "shàngkè", simplified: "上课", english: "to go to class" },
        { target: "睡覺", transliteration: "shuìjiào", simplified: "睡觉", english: "to sleep" },
      ],
    },
    {
      id: "zh-m1-l4-e13",
      type: "explain",
      prompt: "describe your daily routine, in chinese only",
      topic: "describe three things you do every day with times",
      targetLanguageHint: "我每天...點...。",
      modelAnswer: "我每天七點起床，八點上班，晚上十一點睡覺。",
      modelAnswerEnglish: "Every day I get up at seven, go to work at eight, and go to sleep at eleven at night.",
    },
  ],
};

const lesson5: Lesson = {
  id: "zh-m1-l5",
  moduleId: "zh-m1",
  language: "zh",
  title: "food & dining",
  size: "large",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l5-e1",
      type: "match",
      prompt: "match each food word to its meaning",
      pairs: [
        { target: "米飯", transliteration: "mǐfàn", simplified: "米饭", english: "rice" },
        { target: "麵條", transliteration: "miàntiáo", simplified: "面条", english: "noodles" },
        { target: "餃子", transliteration: "jiǎozi", simplified: "饺子", english: "dumplings" },
        { target: "茶", transliteration: "chá", english: "tea" },
        { target: "咖啡", transliteration: "kāfēi", english: "coffee" },
      ],
    },
    {
      id: "zh-m1-l5-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I want to eat dumplings.",
      answer: "我想吃餃子。",
      transliteration: "wǒ xiǎng chī jiǎozi.",
      term: { target: "想", transliteration: "xiǎng", english: "want to (do something)" },
    },
    {
      id: "zh-m1-l5-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "這個很好吃。",
      simplified: "这个很好吃。",
      answer: "This is very delicious.",
      transliteration: "zhège hěn hǎochī.",
      term: { target: "好吃", transliteration: "hǎochī", english: "delicious (of food)" },
    },
    {
      id: "zh-m1-l5-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "我很___，我想喝水。",
      transliteration: "wǒ hěn ___, wǒ xiǎng hē shuǐ.",
      english: "I'm very thirsty, I want to drink water.",
      answer: "渴",
      options: ["渴", "餓", "累", "忙"],
      term: { target: "渴", transliteration: "kě", english: "thirsty" },
    },
    {
      id: "zh-m1-l5-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "服務員，請問，菜單在哪裡？",
      simplified: "服务员，请问，菜单在哪里？",
      transliteration: "fúwùyuán, qǐngwèn, càidān zài nǎlǐ?",
      english: "Waiter, excuse me, where is the menu?",
      term: { target: "请问", transliteration: "qǐngwèn", english: "excuse me, may I ask..." },
    },
    {
      id: "zh-m1-l5-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "我要一碗麵條和一杯茶。",
      question: "What did the speaker order?",
      options: ["Rice and coffee", "Noodles and tea", "Dumplings and water"],
      correctIndex: 1,
    },
    {
      id: "zh-m1-l5-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "這個菜太___了，我不能吃。",
      simplified: "这个菜太___了，我不能吃。",
      transliteration: "zhège cài tài ___ le, wǒ bù néng chī.",
      english: "This dish is too spicy, I can't eat it.",
      answer: "辣",
      options: ["辣", "甜", "好吃", "餓"],
      term: { target: "辣", transliteration: "là", english: "spicy" },
    },
    {
      id: "zh-m1-l5-e8",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I am hungry.",
      answer: "我餓了。",
      transliteration: "wǒ è le.",
      term: { target: "了", transliteration: "le", english: "change-of-state particle (marks a new situation)" },
    },
    {
      id: "zh-m1-l5-e9",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "買單，謝謝。",
      simplified: "买单，谢谢。",
      answer: "Check, please (lit. pay the bill, thanks).",
      transliteration: "mǎidān, xièxie.",
      term: { target: "买单", transliteration: "mǎidān", english: "to pay the bill" },
    },
    {
      id: "zh-m1-l5-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "I want to drink coffee.",
      words: ["我", "想", "喝", "咖啡"],
    },
    {
      id: "zh-m1-l5-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "這個湯太甜了。",
      english: "This soup is too sweet.",
    },
    {
      id: "zh-m1-l5-e12",
      type: "match",
      prompt: "match each dining word to its meaning",
      pairs: [
        { target: "筷子", transliteration: "kuàizi", english: "chopsticks" },
        { target: "服務員", transliteration: "fúwùyuán", simplified: "服务员", english: "waiter" },
        { target: "菜單", transliteration: "càidān", simplified: "菜单", english: "menu" },
        { target: "買單", transliteration: "mǎidān", simplified: "买单", english: "to pay the bill" },
        { target: "好喝", transliteration: "hǎohē", english: "tasty (of a drink)" },
      ],
    },
    {
      id: "zh-m1-l5-e13",
      type: "speak",
      prompt: "say this aloud",
      target: "請問，這個多少錢？",
      simplified: "请问，这个多少钱？",
      transliteration: "qǐngwèn, zhège duōshao qián?",
      english: "Excuse me, how much is this?",
      term: { target: "多少钱", transliteration: "duōshao qián", english: "how much money" },
    },
    {
      id: "zh-m1-l5-e14",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I am a vegetarian.",
      answer: "我吃素。",
      transliteration: "wǒ chī sù.",
      term: { target: "吃素", transliteration: "chī sù", english: "to be vegetarian (lit. 'eat vegetarian')" },
    },
    {
      id: "zh-m1-l5-e15",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "請給我___水。",
      simplified: "请给我___水。",
      transliteration: "qǐng gěi wǒ ___ shuǐ.",
      english: "Please give me a little water.",
      answer: "一點",
      options: ["一點", "很多", "一些", "幾個"],
      term: { target: "一点", transliteration: "yìdiǎn", english: "a little bit" },
    },
    {
      id: "zh-m1-l5-e16",
      type: "listen",
      prompt: "listen and answer",
      audioText: "一共三十五塊五毛錢。",
      question: "How much is the total?",
      options: ["25.50 kuai", "35.50 kuai", "45.50 kuai"],
      correctIndex: 1,
    },
    {
      id: "zh-m1-l5-e17",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "我可以用筷子吃飯。",
      simplified: "我可以用筷子吃饭。",
      answer: "I can eat with chopsticks.",
      transliteration: "wǒ kěyǐ yòng kuàizi chīfàn.",
      term: { target: "筷子", transliteration: "kuàizi", english: "chopsticks" },
    },
    {
      id: "zh-m1-l5-e18",
      type: "reorder",
      prompt: "put the words in order",
      english: "This tea is very tasty.",
      words: ["這個", "茶", "很", "好喝"],
    },
    {
      id: "zh-m1-l5-e19",
      type: "explain",
      prompt: "order a meal in chinese only",
      topic: "order two dishes and a drink, politely, using 我要 and 请问",
      targetLanguageHint: "服務員，我要...和...，謝謝。",
      modelAnswer: "服務員，我要一碗米飯和一份餃子，還要一杯茶，謝謝。",
      modelAnswerEnglish: "Waiter, I'd like a bowl of rice and an order of dumplings, and also a cup of tea, thank you.",
    },
  ],
};

const lesson6: Lesson = {
  id: "zh-m1-l6",
  moduleId: "zh-m1",
  language: "zh",
  title: "home & directions",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l6-e1",
      type: "match",
      prompt: "match each room word to its meaning",
      pairs: [
        { target: "臥室", transliteration: "wòshì", simplified: "卧室", english: "bedroom" },
        { target: "廚房", transliteration: "chúfáng", simplified: "厨房", english: "kitchen" },
        { target: "洗手間", transliteration: "xǐshǒujiān", simplified: "洗手间", english: "bathroom" },
        { target: "客廳", transliteration: "kètīng", simplified: "客厅", english: "living room" },
        { target: "房間", transliteration: "fángjiān", simplified: "房间", english: "room" },
      ],
    },
    {
      id: "zh-m1-l6-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "The kitchen is next to the living room.",
      answer: "廚房在客廳旁邊。",
      transliteration: "chúfáng zài kètīng pángbiān.",
      term: { target: "旁边", transliteration: "pángbiān", english: "next to, beside" },
    },
    {
      id: "zh-m1-l6-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "洗手間在哪裡？",
      simplified: "洗手间在哪里？",
      answer: "Where is the bathroom?",
      transliteration: "xǐshǒujiān zài nǎlǐ?",
      term: { target: "哪里", transliteration: "nǎlǐ", english: "where" },
    },
    {
      id: "zh-m1-l6-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "洗手間在你的___邊，不是右邊。",
      simplified: "洗手间在你的___边，不是右边。",
      transliteration: "xǐshǒujiān zài nǐ de ___ bian, bú shì yòubian.",
      english: "The bathroom is on your left, not the right.",
      answer: "左",
      options: ["左", "右", "前", "後"],
      term: { target: "左边", transliteration: "zuǒbian", english: "left side" },
    },
    {
      id: "zh-m1-l6-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "一直走，然後往右拐。",
      simplified: "一直走，然后往右拐。",
      transliteration: "yìzhí zǒu, ránhòu wǎng yòu guǎi.",
      english: "Go straight, then turn right.",
      term: { target: "一直走", transliteration: "yìzhí zǒu", english: "go straight" },
    },
    {
      id: "zh-m1-l6-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "地鐵站在前面，不遠。",
      question: "Where is the subway station?",
      options: ["In front, not far", "Behind, very far", "On the right side"],
      correctIndex: 0,
    },
    {
      id: "zh-m1-l6-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "請問，去地鐵站怎麼___？",
      simplified: "请问，去地铁站怎么___？",
      transliteration: "qǐngwèn, qù dìtiězhàn zěnme ___?",
      english: "Excuse me, how do I get to the subway station?",
      answer: "走",
      options: ["走", "去", "是", "在"],
      term: { target: "怎么走", transliteration: "zěnme zǒu", english: "how do I get there" },
    },
    {
      id: "zh-m1-l6-e8",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "The bookstore is near here.",
      answer: "書店在這附近。",
      transliteration: "shūdiàn zài zhè fùjìn.",
      term: { target: "附近", transliteration: "fùjìn", english: "nearby" },
    },
    {
      id: "zh-m1-l6-e9",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "銀行在超市後面。",
      simplified: "银行在超市后面。",
      answer: "The bank is behind the supermarket.",
      transliteration: "yínháng zài chāoshì hòumiàn.",
      term: { target: "后面", transliteration: "hòumiàn", english: "behind" },
    },
    {
      id: "zh-m1-l6-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "The bathroom is right there on the right.",
      words: ["洗手間", "就", "在", "右邊"],
    },
    {
      id: "zh-m1-l6-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "廚房在哪裡？",
      english: "Where is the kitchen?",
    },
    {
      id: "zh-m1-l6-e12",
      type: "match",
      prompt: "match each direction word to its meaning",
      pairs: [
        { target: "左邊", transliteration: "zuǒbian", simplified: "左边", english: "left side" },
        { target: "右邊", transliteration: "yòubian", simplified: "右边", english: "right side" },
        { target: "前面", transliteration: "qiánmiàn", english: "front" },
        { target: "後面", transliteration: "hòumiàn", simplified: "后面", english: "behind" },
        { target: "一直走", transliteration: "yìzhí zǒu", english: "go straight" },
      ],
    },
    {
      id: "zh-m1-l6-e13",
      type: "explain",
      prompt: "give directions in chinese only",
      topic: "explain how to get from your house to a nearby place, using 一直走 / 左边 / 右边",
      targetLanguageHint: "先...然後...就在...",
      modelAnswer: "一直走，然後往左拐，地鐵站就在前面。",
      modelAnswerEnglish: "Go straight, then turn left, the subway station is right there in front.",
    },
  ],
};

const lesson7: Lesson = {
  id: "zh-m1-l7",
  moduleId: "zh-m1",
  language: "zh",
  title: "shopping & money",
  size: "medium",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l7-e1",
      type: "match",
      prompt: "match each shopping word to its meaning",
      pairs: [
        { target: "商店", transliteration: "shāngdiàn", english: "store" },
        { target: "衣服", transliteration: "yīfu", english: "clothes" },
        { target: "便宜", transliteration: "piányi", english: "cheap" },
        { target: "貴", transliteration: "guì", simplified: "贵", english: "expensive" },
        { target: "錢", transliteration: "qián", simplified: "钱", english: "money" },
      ],
    },
    {
      id: "zh-m1-l7-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "This dress is too expensive.",
      answer: "這件衣服太貴了。",
      transliteration: "zhè jiàn yīfu tài guì le.",
      term: { target: "贵", transliteration: "guì", english: "expensive" },
    },
    {
      id: "zh-m1-l7-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "這個很便宜。",
      simplified: "这个很便宜。",
      answer: "This is very cheap.",
      transliteration: "zhège hěn piányi.",
      term: { target: "便宜", transliteration: "piányi", english: "cheap" },
    },
    {
      id: "zh-m1-l7-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "我可以___這件衣服嗎？",
      simplified: "我可以___这件衣服吗？",
      transliteration: "wǒ kěyǐ ___ zhè jiàn yīfu ma?",
      english: "Can I try on this piece of clothing?",
      answer: "試穿",
      options: ["試穿", "買", "賣", "穿"],
      term: { target: "试穿", transliteration: "shìchuān", english: "to try on (clothing)" },
    },
    {
      id: "zh-m1-l7-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "請問，可以刷信用卡嗎？",
      simplified: "请问，可以刷信用卡吗？",
      transliteration: "qǐngwèn, kěyǐ shuā xìnyòngkǎ ma?",
      english: "Excuse me, can I pay by credit card?",
      term: { target: "信用卡", transliteration: "xìnyòngkǎ", english: "credit card" },
    },
    {
      id: "zh-m1-l7-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "一共三十五塊錢，您要現金還是信用卡？",
      question: "What payment options are offered?",
      options: ["Cash or credit card", "Only cash", "Only credit card"],
      correctIndex: 0,
    },
    {
      id: "zh-m1-l7-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "我想用___付錢。",
      simplified: "我想用___付钱。",
      transliteration: "wǒ xiǎng yòng ___ fùqián.",
      english: "I want to pay with cash.",
      answer: "現金",
      options: ["現金", "信用卡", "錢", "收據"],
      term: { target: "现金", transliteration: "xiànjīn", english: "cash" },
    },
    {
      id: "zh-m1-l7-e8",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "How much is this?",
      answer: "這個多少錢？",
      transliteration: "zhège duōshao qián?",
      term: { target: "多少", transliteration: "duōshao", english: "how much / how many" },
    },
    {
      id: "zh-m1-l7-e9",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "這個商店在打折。",
      simplified: "这个商店在打折。",
      answer: "This store is having a sale.",
      transliteration: "zhège shāngdiàn zài dǎzhé.",
      term: { target: "打折", transliteration: "dǎzhé", english: "to have a discount / sale" },
    },
    {
      id: "zh-m1-l7-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "I want to buy this book.",
      words: ["我", "想", "買", "這本", "書"],
    },
    {
      id: "zh-m1-l7-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "老闆，能便宜一點嗎？",
      english: "Boss, can it be a little cheaper?",
    },
    {
      id: "zh-m1-l7-e12",
      type: "match",
      prompt: "match each payment word to its meaning",
      pairs: [
        { target: "現金", transliteration: "xiànjīn", simplified: "现金", english: "cash" },
        { target: "信用卡", transliteration: "xìnyòngkǎ", english: "credit card" },
        { target: "找錢", transliteration: "zhǎoqián", simplified: "找钱", english: "to give change" },
        { target: "收據", transliteration: "shōujù", simplified: "收据", english: "receipt" },
        { target: "打折", transliteration: "dǎzhé", english: "discount, sale" },
      ],
    },
    {
      id: "zh-m1-l7-e13",
      type: "explain",
      prompt: "bargain for a lower price, in chinese only",
      topic: "ask how much something costs and ask for a discount",
      targetLanguageHint: "老闆，這個多少錢？能便宜一點嗎？",
      modelAnswer: "老闆，這件衣服多少錢？能便宜一點嗎？",
      modelAnswerEnglish: "Boss, how much is this piece of clothing? Can it be a bit cheaper?",
    },
  ],
};

const lesson8: Lesson = {
  id: "zh-m1-l8",
  moduleId: "zh-m1",
  language: "zh",
  title: "weather, small talk & hobbies bridge",
  size: "large",
  kind: "core",
  exercises: [
    {
      id: "zh-m1-l8-e1",
      type: "match",
      prompt: "match each weather word to its meaning",
      pairs: [
        { target: "熱", transliteration: "rè", simplified: "热", english: "hot" },
        { target: "冷", transliteration: "lěng", english: "cold" },
        { target: "下雨", transliteration: "xiàyǔ", english: "to rain" },
        { target: "下雪", transliteration: "xiàxuě", english: "to snow" },
        { target: "晴天", transliteration: "qíngtiān", english: "sunny day" },
      ],
    },
    {
      id: "zh-m1-l8-e2",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "Today's weather is very good.",
      answer: "今天的天氣很好。",
      transliteration: "jīntiān de tiānqì hěn hǎo.",
      term: { target: "天气", transliteration: "tiānqì", english: "weather" },
    },
    {
      id: "zh-m1-l8-e3",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "明天會下雨。",
      simplified: "明天会下雨。",
      answer: "It will rain tomorrow.",
      transliteration: "míngtiān huì xiàyǔ.",
      term: { target: "下雨", transliteration: "xiàyǔ", english: "to rain" },
    },
    {
      id: "zh-m1-l8-e4",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "冬天很___，夏天很熱。",
      simplified: "冬天很___，夏天很热。",
      transliteration: "dōngtiān hěn ___, xiàtiān hěn rè.",
      english: "Winter is very cold, summer is very hot.",
      answer: "冷",
      options: ["冷", "熱", "晴", "陰"],
      term: { target: "冷", transliteration: "lěng", english: "cold" },
    },
    {
      id: "zh-m1-l8-e5",
      type: "speak",
      prompt: "say this aloud",
      target: "今天颳風，也有點陰。",
      simplified: "今天刮风，也有点阴。",
      transliteration: "jīntiān guāfēng, yě yǒudiǎn yīn.",
      english: "Today it's windy, and also a bit cloudy.",
      term: { target: "刮风", transliteration: "guāfēng", english: "to be windy" },
    },
    {
      id: "zh-m1-l8-e6",
      type: "listen",
      prompt: "listen and answer",
      audioText: "明天是晴天，不會下雨。",
      question: "What will tomorrow's weather be like?",
      options: ["Sunny, no rain", "Rainy all day", "Snowy and cold"],
      correctIndex: 0,
    },
    {
      id: "zh-m1-l8-e7",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "週末我喜歡___書。",
      simplified: "周末我喜欢___书。",
      transliteration: "zhōumò wǒ xǐhuan ___ shū.",
      english: "On weekends I like to read books.",
      answer: "看",
      options: ["看", "聽", "打", "踢"],
      term: { target: "看书", transliteration: "kànshū", english: "to read (books)" },
    },
    {
      id: "zh-m1-l8-e8",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I like listening to music.",
      answer: "我喜歡聽音樂。",
      transliteration: "wǒ xǐhuan tīng yīnyuè.",
      term: { target: "听音乐", transliteration: "tīng yīnyuè", english: "to listen to music" },
    },
    {
      id: "zh-m1-l8-e9",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "他週末喜歡打籃球。",
      simplified: "他周末喜欢打篮球。",
      answer: "He likes to play basketball on the weekend.",
      transliteration: "tā zhōumò xǐhuan dǎ lánqiú.",
      term: { target: "打篮球", transliteration: "dǎ lánqiú", english: "to play basketball" },
    },
    {
      id: "zh-m1-l8-e10",
      type: "reorder",
      prompt: "put the words in order",
      english: "I like watching movies.",
      words: ["我", "喜歡", "看", "電影"],
    },
    {
      id: "zh-m1-l8-e11",
      type: "dictation",
      prompt: "type what you hear",
      target: "你週末喜歡做什麼？",
      english: "What do you like to do on the weekend?",
    },
    {
      id: "zh-m1-l8-e12",
      type: "match",
      prompt: "match each hobby to its meaning",
      pairs: [
        { target: "看書", transliteration: "kànshū", simplified: "看书", english: "to read (books)" },
        { target: "看電影", transliteration: "kàn diànyǐng", simplified: "看电影", english: "to watch movies" },
        { target: "聽音樂", transliteration: "tīng yīnyuè", simplified: "听音乐", english: "to listen to music" },
        { target: "打籃球", transliteration: "dǎ lánqiú", simplified: "打篮球", english: "to play basketball" },
        { target: "游泳", transliteration: "yóuyǒng", english: "to swim" },
      ],
    },
    {
      id: "zh-m1-l8-e13",
      type: "cloze",
      prompt: "fill in the blank",
      sentence: "我週末喜歡___足球。",
      simplified: "我周末喜欢___足球。",
      transliteration: "wǒ zhōumò xǐhuan ___ zúqiú.",
      english: "On weekends I like to play soccer.",
      answer: "踢",
      options: ["踢", "打", "看", "聽"],
      term: { target: "踢足球", transliteration: "tī zúqiú", english: "to play soccer" },
    },
    {
      id: "zh-m1-l8-e14",
      type: "translate",
      prompt: "translate to chinese",
      direction: "to-target",
      source: "I like swimming and traveling.",
      answer: "我喜歡游泳和旅遊。",
      transliteration: "wǒ xǐhuan yóuyǒng hé lǚyóu.",
      term: { target: "旅游", transliteration: "lǚyóu", english: "to travel" },
    },
    {
      id: "zh-m1-l8-e15",
      type: "speak",
      prompt: "say this aloud",
      target: "你週末有空嗎？我們一起運動吧。",
      simplified: "你周末有空吗？我们一起运动吧。",
      transliteration: "nǐ zhōumò yǒu kòng ma? wǒmen yìqǐ yùndòng ba.",
      english: "Are you free this weekend? Let's exercise together.",
      term: { target: "运动", transliteration: "yùndòng", english: "sports, to exercise" },
    },
    {
      id: "zh-m1-l8-e16",
      type: "listen",
      prompt: "listen and answer",
      audioText: "我的愛好是看書和聽音樂，你呢？",
      question: "What are the speaker's hobbies?",
      options: ["Reading and listening to music", "Swimming and soccer", "Basketball and travel"],
      correctIndex: 0,
    },
    {
      id: "zh-m1-l8-e17",
      type: "translate",
      prompt: "translate to english",
      direction: "to-english",
      source: "你的愛好是什麼？",
      simplified: "你的爱好是什么？",
      answer: "What is your hobby?",
      transliteration: "nǐ de àihào shì shénme?",
      term: { target: "爱好", transliteration: "àihào", english: "hobby" },
    },
    {
      id: "zh-m1-l8-e18",
      type: "reorder",
      prompt: "put the words in order",
      english: "What do you think today's weather is like?",
      words: ["你", "覺得", "今天", "天氣", "怎麼樣"],
    },
    {
      id: "zh-m1-l8-e19",
      type: "explain",
      prompt: "talk about the weather and your weekend hobby, in chinese only",
      topic: "describe today's weather and one thing you like to do on weekends",
      targetLanguageHint: "今天...，週末我喜歡...",
      modelAnswer: "今天天氣很好，是晴天。週末我喜歡看書和聽音樂。",
      modelAnswerEnglish: "The weather is very nice today, it's sunny. On the weekends I like reading books and listening to music.",
    },
  ],
};

export const zhLessons: Lesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
  lesson5,
  lesson6,
  lesson7,
  lesson8,
];

export const zhModules = buildModules(
  "zh",
  zhLessons.map((l) => l.id)
);

// ---------- Quote bank ----------
// 8 short quotes from the Dao De Jing (Laozi) and the Analects (Confucius) —
// traditional Chinese (with simplified given parenthetically alongside
// transliteration) + pinyin with tone marks + faithful English translation.
export const zhQuotes: Quote[] = [
  {
    id: "zh-q1",
    language: "zh",
    native: "道可道，非常道。名可名，非常名。",
    transliteration: "Dào kě dào, fēicháng dào. Míng kě míng, fēicháng míng.",
    english: "The Tao that can be spoken is not the eternal Tao. The name that can be named is not the eternal name.",
    source: "Dao De Jing, ch. 1",
    author: "Laozi",
  },
  {
    id: "zh-q2",
    language: "zh",
    native: "千里之行，始於足下。",
    simplified: "千里之行，始于足下。",
    transliteration: "Qiān lǐ zhī xíng, shǐ yú zú xià.",
    english: "A journey of a thousand miles begins with a single step.",
    source: "Dao De Jing, ch. 64",
    author: "Laozi",
  },
  {
    id: "zh-q3",
    language: "zh",
    native: "知人者智，自知者明。",
    transliteration: "Zhī rén zhě zhì, zì zhī zhě míng.",
    english: "Knowing others is wisdom; knowing yourself is enlightenment.",
    source: "Dao De Jing, ch. 33",
    author: "Laozi",
  },
  {
    id: "zh-q4",
    language: "zh",
    native: "上善若水，水善利萬物而不爭。",
    simplified: "上善若水，水善利万物而不争。",
    transliteration: "Shàng shàn ruò shuǐ, shuǐ shàn lì wàn wù ér bù zhēng.",
    english: "The highest good is like water; water benefits all things without contending.",
    source: "Dao De Jing, ch. 8",
    author: "Laozi",
  },
  {
    id: "zh-q5",
    language: "zh",
    native: "學而時習之，不亦說乎？",
    simplified: "学而时习之，不亦说乎？",
    transliteration: "Xué ér shí xí zhī, bú yì yuè hū?",
    english: "Is it not a pleasure to learn and practice what is learned time and again?",
    source: "Analects, 1.1",
    author: "Confucius",
  },
  {
    id: "zh-q6",
    language: "zh",
    native: "知之為知之，不知為不知，是知也。",
    simplified: "知之为知之，不知为不知，是知也。",
    transliteration: "Zhī zhī wéi zhī zhī, bù zhī wéi bù zhī, shì zhī yě.",
    english: "When you know a thing, hold that you know it; and when you do not know a thing, allow that you do not know it — this is knowledge.",
    source: "Analects, 2.17",
    author: "Confucius",
  },
  {
    id: "zh-q7",
    language: "zh",
    native: "見賢思齊焉，見不賢而內自省也。",
    simplified: "见贤思齐焉，见不贤而内自省也。",
    transliteration: "Jiàn xián sī qí yān, jiàn bù xián ér nèi zì xǐng yě.",
    english: "When you see a person of worth, think of how to become their equal; when you see someone unworthy, examine your own conduct.",
    source: "Analects, 4.17",
    author: "Confucius",
  },
  {
    id: "zh-q8",
    language: "zh",
    native: "己所不欲，勿施於人。",
    simplified: "己所不欲，勿施于人。",
    transliteration: "Jǐ suǒ bú yù, wù shī yú rén.",
    english: "Do not impose on others what you yourself do not desire.",
    source: "Analects, 15.24",
    author: "Confucius",
  },
];
